---
date: today
---

Este documento es la continuación de C:/Prog/tesis/25_cap2_metodologia_v3_con_enoe_2T2025.qmd

Paquetes requeridos

```{r}
#| label: setup
#| warning: false
#| message: false

# Librerías requeridas ========================================================

# manejo de datos
library(tidyverse)
# importación de Excel
library(readxl)
# paleta de colores
library(RColorBrewer)
# trabajar encuesta compleja dentro de tidyverse 
library(srvyr)
# regresión a encuesta compleja
library(survey)
# convertir a porcentaje dentro de mutate
library(scales) 
library(gt)
# mapas geográficos
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
```

Fuente de datos

```{r}
# Fuente de datos =============================================================

# PIB vs egresados (INEGI; ANUIES)
pib_vs_egres <- read_csv(
  "datos/PIBvsEgresados.csv",
  col_types = cols(.default = col_double())
)



# 3. sociodemográfica
sdem <- read_csv(
  "datos/ENOE_SDEMT225.csv",
  col_types = cols(.default = col_character())
)

# 4. ocupación y empleo I
coe1 <- read_csv(
  "datos/ENOE_COE1T225.csv",
  col_types = cols(.default = col_character())
)

# 5. ocupación y empleo II
coe2 <- read_csv(
  "datos/ENOE_COE2T225.csv",
  col_types = cols(.default = col_character())
)

# tabla comparativa entre SINCO-11 y CIUO-08 (INEGI, 2012)
sinco11_ciuo08 <- read_csv(
  "datos/sinco11_a_ciuo08.csv",
  col_types = cols(.default = col_character()),
  na = "NA"
)

# tabla equivalencia entre v11 y v19 de SINCO (INEGI, 2020: 359-394)
sinco19_11 <- read_csv(
  "datos/sinco19_a_sinco11.csv",
  col_types = cols(.default = col_character()),
  na = "NA"
)

# CIUO-08 (ILO, s/f)
ciuo08 <- read_xlsx(
  "datos/ISCO.xlsx",
  sheet = 2,
  col_types = "text"
)
```

Construcción

Tablas

```{r}
# Construcción ================================================================

## Tablas ---------------------------------------------------------------------

# población de 12 y más para unir sdem y coe INEGI(2023:9)
pob_12ymas <- sdem |> 
  mutate(edad = as.integer(eda)) |> 
  filter(
    r_def == "0",
    c_res != "2",
    between(edad, 12, 98)
  )

# población total INEGI(2023:21)
pob_total <- sdem |> 
  filter(
    r_def == "0",
    # es igual a (c_res == "1" | c_res == "3")
    c_res != "2"
  )

# unión de sdem y coe INEGI(2023:9)
completo <- pob_12ymas |>
  full_join(coe1, by = c("tipo", "mes_cal", "cd_a", "ent", "con", "v_sel", "n_hog", "h_mud", "n_ren")) |>
  full_join(coe2, by = c("tipo", "mes_cal", "cd_a", "ent", "con", "v_sel", "n_hog", "h_mud", "n_ren"))

# población de 15 años y más INEGI(2023:21)
# para seleccionar población ocupada INEGI(2023:21)
pob_15ymas <- completo |> 
  filter(
    r_def.x == "0",
    c_res != "2",
    between(edad, 15, 98)
  )

# población ocupada INEGI(2023: 21)
ocupada <- pob_15ymas |> 
  filter(clase2 == 1)

# se limpia tabla comparativa de CIUO-08 con SINCO-11
sinco11_ciuo08 <- sinco11_ciuo08 |>
  select(sinco11, ciuo08) |>
  # nos quedamos con grupo unitario
  filter(str_length(sinco11) == 4) |>
  # se renombran variables para unión
  rename(
    "s11_unit" = "sinco11",
    "c08_unit" = "ciuo08"
  )

# se limpia tabla de equivalencia entre v11 y v19 de SINCO
sinco19_11 <- sinco19_11 |>
  select(sinco_19, sinco_11) |>
  # nos quedamos con grupo unitario
  filter(str_length(sinco_19) == 4) |>
  # se renombran variables para unión
  rename(
    "s19_unit" = "sinco_19",
    "s11_unit" = "sinco_11"
  )
```

Variables

```{r}
## Variables ------------------------------------------------------------------

# grupos de edad
ocupada <- ocupada |> 
  mutate(
    # 98 y 99 indican edad no especificada
    # se convierten a NA para evitar errores de cálculo en exper
    edad = if_else(edad == 98 | edad == 99, NA, edad),
    # para crear grupo de jóvenes 25-34 años OECD(2019: 135) 
    # y comparar incidencia por grupos de edad
    edad_7g = case_when(
      between(edad, 15, 24) ~ 1,
      between(edad, 25, 34) ~ 2,
      between(edad, 35, 44) ~ 3,
      between(edad, 45, 54) ~ 4,
      between(edad, 55, 64) ~ 5,
      between(edad, 65, 97) ~ 6,
      # valor 7 indica no especificado
      TRUE ~ 7
    )
  )

# campos de formación académica a 1 dígito de CMPE (INEGI, 2016: 13)
ocupada <- ocupada %>% 
  mutate(
    campo_amplio = if_else(str_length(cs_p14_c) == 5, str_c("0", cs_p14_c), cs_p14_c)
  ) %>% 
  separate(
    campo_amplio,
    # campo amplio a 1 dígito de CMPE
    into = c("campo_amplio", "res"),
    sep = 2
  ) %>% 
  select(-res)

# ocupaciones a 1 dígito de SINCO (INEGI, 2019: 22)
ocupada <- ocupada %>% 
  mutate(division = p3) %>% 
  separate(
    division, 
    into = c("division", "res"),
    sep = 1
  ) %>% 
  select(-res) |> 
  mutate(
    # ocupación 9999 pertenece a ocupaciones no especificadas (INEGI, 2020: 356)
    # se crea una división que contiene casos no especificados
    division = if_else(p3 == "9999", "10", division)
  )

# nivel de estudios en términos de CINE-11 (UNESCO, 2013: 22) 
ocupada <- ocupada |> 
  mutate(
    # nivel escolar
    educacion = as.integer(cs_p13_1),
    # 99 pasa a NA para evitar 99 - edu_req
    educacion = if_else(educacion != 99, educacion, NA),
    # cambian los valores de cs_p15 para que coincidan con cs_p13_1
    edu_previa = case_when(
      # primaria
      cs_p15 == "1" ~ 2,
      # secundaria
      cs_p15 == "2" ~ 3,
      # preparatoria
      cs_p15 == "3" ~ 4,
      TRUE ~ NA
    ),
    educacion = case_when(
      # si no concluyó sus estudios y reporta educación previa
      # se le asigna el nivel reportado en cs_p15 
      cs_p16 == "2" & !is.na(edu_previa) ~ edu_previa,
      # si no concluyó sus estudios y no reporta educación previa
      # doctorado baja a maestría
      cs_p16 == "2" & is.na(edu_previa) & educacion == 9 ~ 8,
      # maestría baja a licenciatura
      cs_p16 == "2" & is.na(edu_previa) & educacion == 8 ~ 7,
      # licenciatura baja a preparatoria
      cs_p16 == "2" & is.na(edu_previa) & educacion == 7 ~ 4,
      # carrera técnica baja a preparatoria
      cs_p16 == "2" & is.na(edu_previa) & educacion == 6 ~ 4,
      # normal baja a preparatoria
      cs_p16 == "2" & is.na(edu_previa) & educacion == 5 ~ 4,
      # preparatoria baja a secundaria
      cs_p16 == "2" & is.na(edu_previa) & educacion == 4 ~ 3,
      # secundaria baja a primaria 
      cs_p16 == "2" & is.na(edu_previa) & educacion == 3 ~ 2,
      # primaria baja a preescolar
      cs_p16 == "2" & is.na(edu_previa) & educacion == 2 ~ 1,
      # preescolar baja a ninguna
      cs_p16 == "2" & is.na(edu_previa) & educacion == 1 ~ 0,
      # si concluyó se le asigna el nivel educativo reportado
      TRUE ~ educacion
    ),
    # 5 pasa a 7 para método objetivo a 4 dígitos
    educacion = if_else(educacion == 5, 7, educacion)
  ) 

# agrupar estados por regiones (CESOP, 2022: 13)
ocupada <- ocupada %>% 
  mutate(
    regiones = case_when(
      # centro
      ent == 11 | ent == 22 | ent == 13 | ent == 15 | ent == 9 | 
        ent == 17 | ent == 29 | ent == 21 ~ "1",
      # centro-norte
      ent == 14 | ent == 1 | ent == 6 | ent == 16 | ent == 24 ~ "2",
      # norte
      ent == 2 | ent == 26 | ent == 8 | ent == 5 | ent == 19 | 
        ent == 28 ~ "3",
      # norte-occidente
      ent == 3 | ent == 25 | ent == 18 | ent == 10 | ent == 32 ~ "4",
      # sur
      ent == 12 | ent == 20 | ent == 7 | ent == 30 | ent == 27 | 
        ent == 4 | ent == 31 | ent == 23 ~ "5",
      TRUE ~ NA
    )
  )

## Limpieza ====================================================================

ocupada <- ocupada %>% 
  mutate(
    # años de escolaridad (INEGI, 2024: 25)
    anios_estudios = as.integer(anios_esc),
    # 99 indica no especificado, se convierte a NA
    anios_estudios = if_else(anios_estudios != 99, anios_estudios, NA),
    # ponderador trimestral
    fac_tri = as.double(fac_tri),
    # ingreso mensual
    ingreso_mensual = as.double(ingocup),
    # 0 pasa a NA ya que 0 en ingocup es igual a NA en p6b2
    ingreso_mensual = if_else(ingreso_mensual != 0, ingreso_mensual, NA),
    # resto de variables explicativas
    # horas trabajadas
    # 999 indica no especificado, se convierte a NA (INEGI, 2024:81)
    horas_lab = if_else(p5b_thrs != 999, p5b_thrs, NA),
    horas_lab = as.double(horas_lab),
    # experiencia laboral potencial
    # Zamudio e Islas(1999) y Mincer(1974)
    exper = edad - anios_estudios - 6,
    mujer = if_else(sex == 2, 1, 0),
    casada = if_else(e_con == 5, 1, 0),
    # situación de hogar (INEGI, 2020:37)
    jefe_hogar = if_else(par_c == 101, 1, 0),
    division = factor(division),
    campo_amplio = factor(campo_amplio),
    # posición en la ocupacion (INEGI, 2024: 19)
    pos_ocu = factor(pos_ocu),
    # sector económico agregado (INEGI, 2024: 20)
    sector_eco = factor(rama_est1),
    # tamaño de unidad económica (INEGI, 2024: 21)
    tamanio = case_when(
      # valores 2 y 3 pertenecen a micronegocios
      ambito2 == 2 | ambito2 == 3 ~ "1",
      # valores 0 y 8 indican no especificado
      ambito2 == 0 | ambito2 == 8 ~ "8",
      TRUE ~ ambito2
    ),
    tamanio = factor(tamanio),
    # empleo informal (INEGI, 2024: 26)
    informal = if_else(emp_ppal == 1, "1", "0"),
    # nivel educativo
    educacion = factor(educacion),
    # regiones
    regiones = factor(regiones),
    # duración de la jornada laboral (INEGI, 2024: 21)
    jornada = factor(dur_est),
    # tipo de unidad económica (INEGI, 2024: 21)
    unidad_eco = if_else(tue2 == 0, "8", tue2),
    unidad_eco = factor(unidad_eco)
  )
```

Ya no arrojó problemas !!!

Falta método objetivo, criterio, incidencia, pero en teoría ya no existirían problemas

