<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-07">

<title>c3_v3_acopio_v2</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="29_C3_V3_acopio_v2_files/libs/clipboard/clipboard.min.js"></script>
<script src="29_C3_V3_acopio_v2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="29_C3_V3_acopio_v2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="29_C3_V3_acopio_v2_files/libs/quarto-html/popper.min.js"></script>
<script src="29_C3_V3_acopio_v2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="29_C3_V3_acopio_v2_files/libs/quarto-html/anchor.min.js"></script>
<link href="29_C3_V3_acopio_v2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="29_C3_V3_acopio_v2_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="29_C3_V3_acopio_v2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="29_C3_V3_acopio_v2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="29_C3_V3_acopio_v2_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Este documento tiene como objetivo servir de apoyo para la escritura de la versión 3 del capítulo 3 Resultados</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/7_figuras_v2.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>INCIDENCIA GENERAL</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_tot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  edu_mismatch_obj     n     tot    prop
             &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1                0  6944 2125052 0.477  
2                1  7971 2268988 0.509  
3                2    19    6362 0.00143
4               NA   204   53403 0.0120 </code></pre>
</div>
</div>
<p>El 50.9% de jóvenes egresados de educación superior se encuentran en ocupaciones que requieren una educación menor</p>
<p>El 47.7% están adecuadamente emparejados.</p>
<p>El 47.7% no presenta desajuste entre la educación que poseen y la requerida por la ocupación</p>
<p>Los resultados muestran que 1 de cada 2 jóvenes egresados presentan desajuste educativo, es decir, la educación que poseen es distinta a la requerida por la ocupación.</p>
<p>Los resultados muestran que una parte considerable de jóvenes egresados presentan desajuste educativo</p>
<p>POR GÉNERO</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_genero</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
# Groups:   mujer [2]
  mujer edu_mismatch_obj     n     tot    prop
  &lt;dbl&gt;            &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     0                0  3237 1010845 0.462  
2     0                1  4035 1146639 0.524  
3     0                2    11    3296 0.00151
4     0               NA   112   25590 0.0117 
5     1                0  3707 1114207 0.491  
6     1                1  3936 1122349 0.495  
7     1                2     8    3066 0.00135
8     1               NA    92   27813 0.0123 </code></pre>
</div>
</div>
<p>El 49.1% de las jóvenes están adecuadamente emparejadas a la ocupación. Por su parte, el 46.2% de los hombres lo están.</p>
<p>En cuanto a la sobrecalificación, existen más hombres sobrecalificados que mujeres. Los primeros presentan un porcentaje de 52.4%, mientras que las mujeres 49.5% [esta diferencia es estadísticamente significativa?]</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_inc_svy_grp</span>(datos_svy, edu_mismatch_obj, mujer)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
# Groups:   edu_mismatch_obj [4]
  edu_mismatch_obj mujer     n     tot  prop
             &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
1                0     0  3237 1010845 0.476
2                0     1  3707 1114207 0.524
3                1     0  4035 1146639 0.505
4                1     1  3936 1122349 0.495
5                2     0    11    3296 0.518
6                2     1     8    3066 0.482
7               NA     0   112   25590 0.479
8               NA     1    92   27813 0.521</code></pre>
</div>
</div>
<p>Del total de jóvenes sobrecalificados, el 49.5% son mujeres, mientras que 50.5% son hombres.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tbl_est_desc_genero</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  mujer     n     tot  prop
  &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
1     0  7395 2186370 0.491
2     1  7743 2267435 0.509</code></pre>
</div>
</div>
<p>Cabe señalar que no existe tanta diferencia de género en la composición de la muestra. Del total de observaciones, el 50.9% son mujeres y 49.1% son hombres.</p>
<p>[Recuerda que puede obtenerse el porcentaje general, como si fuera una media ponderada, así</p>
<p><span class="math display">\[
=(\% muestra\_muj * \% over\_muj) + ( \% muestra\_hom * \% over\_hom) \\
=\left(0.5091\ast0.495\right)+\left(0.4908\ast0.524\right) \\
=0.509\ =\ 50.9\%
\]</span></p>
<p>Que es igual al porcentaje general</p>
<p>Donde: <span class="math inline">\(%over%\)</span>, se obtiene de grupo -&gt; desajuste</p>
<p>]</p>
<p>POR EDAD</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fig_inc_edad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): font family
not found in Windows font database</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los resultados son relativamente acordes a la evidencia sugerida por la literatura, donde el porcentaje de individuos sobrecalificados disminuye conforme aumenta la edad de la muestra.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_edad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 39 × 5
# Groups:   edad [10]
    edad edu_mismatch_obj     n    tot     prop
   &lt;int&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1    25                0   571 165771 0.421   
 2    25                1   816 221121 0.562   
 3    25                2     2    453 0.00115 
 4    25               NA    25   6032 0.0153  
 5    26                0   619 187076 0.457   
 6    26                1   786 220196 0.538   
 7    26                2     1    142 0.000347
 8    26               NA    15   2157 0.00527 
 9    27                0   657 194436 0.453   
10    27                1   861 229175 0.534   
# ℹ 29 more rows</code></pre>
</div>
</div>
<p>En ese sentido, el 56.2% de jóvenes de 25 años están sobrecalificados y en el caso de 34 años, el 50.3% lo está; una disminución del 10.5%.</p>
<p>Sin embargo, la tendencia no es tan clara o uniforme. En algunos casos, vuelve a incrementarse el porcentaje de sobrecalificados. Por ejemplo, en la edad de 28 años existen 51.2% de sobrecalificados, pero a la edad siguiente (29 años) se incrementa hasta 54.7%, es decir, un incremento del 6.8%.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.503</span> <span class="sc">/</span> <span class="fl">0.562</span> <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1049822</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.547</span> <span class="sc">/</span> <span class="fl">0.512</span> <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06835938</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_edad <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variacion =</span> prop <span class="sc">/</span> <span class="fu">lag</span>(prop) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
    edad edu_mismatch_obj     n    tot  prop variacion
   &lt;int&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
 1    25                1   816 221121 0.562  NA      
 2    26                1   786 220196 0.538  -0.0436 
 3    27                1   861 229175 0.534  -0.00659
 4    28                1   813 229462 0.512  -0.0405 
 5    29                1   816 244764 0.547   0.0672 
 6    30                1   847 235696 0.485  -0.113  
 7    31                1   791 227869 0.478  -0.0149 
 8    32                1   789 243036 0.504   0.0548 
 9    33                1   725 201158 0.446  -0.116  
10    34                1   727 216511 0.503   0.127  </code></pre>
</div>
</div>
<p>En los casos donde existen mayor variación son los siguientes. De 29 a 30 años, disminuye 11.3% el porcentaje de sobrecalificados, dado que pasa de 54.7% a 48.5%.</p>
<p>Asimismo, de 32 a 33 años también existe una reducción del 11.6% de sobrecalificados, ya que pasa de 50.4% a 44.6%.</p>
<p>Por su parte, de 33 a 34 años se incrementa 12.7% el número de sobrecalificados, debido a que pasa de 44.6% a 50.3%.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_edad <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">edu_mismatch_obj =</span> <span class="fu">factor</span>(edu_mismatch_obj)) <span class="sc">|&gt;</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> edad, <span class="at">y =</span> prop)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#314763"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#314763"</span>) <span class="sc">+</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nota: no utilizo el método por defecto de <code>geom_smooth</code>, muestro el comportamiento de los datos a través de ajustarlos por MCO</p>
<p>Ajustando los datos a un modelo de regresión lineal, se observa que en promedio el porcentaje de sobrecalificados disminuye conforme aumenta la edad del individuo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> tbl_inc_edad <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>model_inc_edad <span class="ot">&lt;-</span> <span class="fu">lm</span>(prop <span class="sc">~</span> edad, <span class="at">data =</span> df)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(model_inc_edad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prop ~ edad, data = df)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.033416 -0.017482 -0.002191  0.014604  0.032334 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.777797   0.077440  10.044 8.22e-06 ***
edad        -0.009047   0.002613  -3.463  0.00853 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02373 on 8 degrees of freedom
Multiple R-squared:  0.5998,    Adjusted R-squared:  0.5498 
F-statistic: 11.99 on 1 and 8 DF,  p-value: 0.008533</code></pre>
</div>
</div>
<p>En específico, un año adicional en la edad de la muestra disminuye, en promedio, 0.9% el porcentaje de sobrecalificados, manteniendo los demás factores como constantes</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>model_inc_edad<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)         edad 
 0.777796860 -0.009047219 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.009047219</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9047219</code></pre>
</div>
</div>
<p>Por lo tanto, aunque la tendencia no sea tan clara, en promedio, conforme aumenta la edad del individuo disminuye el porcentaje de sobrecalificados.</p>
<p>No obstante, el porcentaje sigue siendo elevado el porcentaje observado es de 50.3% y el porcentaje estimado es de 47.0%, es decir, en la edad de 34 años el porcentaje de sobrecalificados, en promedio, es de 47.0%.</p>
<p>En ambos casos, la incidencia sigue siendo considerable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model_inc_edad<span class="sc">$</span>fitted.values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
0.5516164 0.5425692 0.5335220 0.5244747 0.5154275 0.5063803 0.4973331 0.4882859 
        9        10 
0.4792386 0.4701914 </code></pre>
</div>
</div>
<p>¿Cómo es el comportamiento de la población total ocupada?</p>
<p>Primero, se construye la tabla <code>general</code>. Por fortuna, el archivo “C:/Prog/tesis/scripts/6_cuadros_v3.R” ya está casi definida la tabla con la que deseamos trabajar. Queda pendiente definir las variables como factor y los datos como tipo survey</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>general2 <span class="ot">&lt;-</span> <span class="fu">convertir_a_factor</span>(general)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>general_svy <span class="ot">&lt;-</span> <span class="fu">definir_encuesta</span>(general2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Después, se calcula la incidencia general para conocer el panorama</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_incidencia_svy_tot</span>(general_svy, edu_mismatch_obj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  edu_mismatch_obj      n      tot   prop
             &lt;dbl&gt;  &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;
1                0 114025 35320887 0.594 
2                1  40133 12033003 0.202 
3                2  33958 11292231 0.190 
4               NA   2571   794639 0.0134</code></pre>
</div>
</div>
<p>El 20.2% de la población ocupada está sobrecalificada, mientras que el 59.4% está adecuadamente emparejada.</p>
<p>Ahora sí, se valida la incidencia por edad</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inc_gral &lt;- general_svy |&gt; </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   filter(over_obj == 1) |&gt; </span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   calcular_inc_svy_des(edad, over_obj)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inc_gral |&gt; </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   ungroup() |&gt; </span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarise(tot = sum(tot))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Esa no es el total de la población ocupada, se valida con la incidencia general</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>inc_gral <span class="ot">&lt;-</span> <span class="fu">calcular_incidencia_svy_tot</span>(general_svy, edu_mismatch_obj)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>inc_gral <span class="sc">|&gt;</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(tot))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       tot
     &lt;dbl&gt;
1 59440760</code></pre>
</div>
</div>
<p>Exacto! Sí son 59.4 millones. Entonces no puedo aplicar la fórmula, haré el cálculo manual</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>general_svy <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       tot
     &lt;dbl&gt;
1 59440760</code></pre>
</div>
</div>
<p>Sí se puede trabajar con los verbos del <code>tidyverse</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>inc_gral_edad <span class="ot">&lt;-</span> general_svy <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(edad, over_obj) <span class="sc">|&gt;</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>inc_gral_edad <span class="sc">|&gt;</span> </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(over_obj) <span class="sc">|&gt;</span> </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(tot)) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  over_obj      tot
     &lt;dbl&gt;    &lt;dbl&gt;
1        0 46613118
2        1 12033003
3       NA   794639</code></pre>
</div>
</div>
<p>Se observa que sí estaba bien. El código anterio solo mostraba el total de sobrecalificados.</p>
<p>Bueno, ahora se calcula porcentaje</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>inc_gral_edad <span class="ot">&lt;-</span> inc_gral_edad <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(edad) <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se grafica</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>inc_gral_edad <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">over_obj =</span> <span class="fu">factor</span>(over_obj)) <span class="sc">|&gt;</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> edad, <span class="at">y =</span> prop)) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#314763"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#314763"</span>) <span class="sc">+</span> </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ajustando los datos a un modelo de regresión lineal tipo MCO, en promedio también disminuye el porcentaje de sobrecalificados.</p>
<p>Se valida valor extremo</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>inc_gral_edad <span class="sc">|&gt;</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> edad <span class="sc">&gt;</span> <span class="dv">80</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
# Groups:   edad [8]
   edad over_obj   tot   prop
  &lt;int&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1    81        1   458 0.0154
2    82        1   505 0.0202
3    83        1   488 0.0154
4    84        1   900 0.0354
5    86        1  1762 0.0939
6    87        1   444 0.0540
7    89        1  1287 0.205 
8    97        1   573 0.452 </code></pre>
</div>
</div>
<p>El valor <code>97</code> NO indica valor no especificado. Si es una edad válida en la muestra.</p>
<p>Por tanto, la relación entre la edad y la sobrecalificación presenta una tendencia cóncava hacia arriba donde en los primeros y últimos años de edad laboral existe una elevada proporción de individuos sobrecalificados, pero conforme posteriormente (anteriormente) disminuye dicho porcentaje</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>df_2 <span class="ot">&lt;-</span> inc_gral_edad <span class="sc">|&gt;</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>model_inc_edad_gral <span class="ot">&lt;-</span> <span class="fu">lm</span>(prop <span class="sc">~</span> edad, <span class="at">data =</span> df_2)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(model_inc_edad_gral)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prop ~ edad, data = df_2)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.05905 -0.02537 -0.01132  0.00670  0.43901 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.3459281  0.0191204   18.09  &lt; 2e-16 ***
edad        -0.0034334  0.0003412  -10.06 2.26e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.06363 on 72 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.5844,    Adjusted R-squared:  0.5787 
F-statistic: 101.3 on 1 and 72 DF,  p-value: 2.265e-15</code></pre>
</div>
</div>
<p>Con datos de la población total ocupada, un aumento en la edad del individuo disminuye, en promedio, 0.3% el porcentaje de sobrecalificados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>model_inc_edad_gral<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)         edad 
 0.345928125 -0.003433419 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.003433419</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3433419</code></pre>
</div>
</div>
<p>POR NIVEL EDUCATIVO</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_educacion</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
# Groups:   educacion [4]
   educacion edu_mismatch_obj     n     tot   prop
   &lt;fct&gt;                &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1 6                        0    73   22055 0.309 
 2 6                        1   146   42105 0.589 
 3 6                        2    19    6362 0.0890
 4 6                       NA     3     955 0.0134
 5 7                        0  6256 1912714 0.465 
 6 7                        1  7577 2150045 0.523 
 7 7                       NA   190   47225 0.0115
 8 8                        0   555  177563 0.699 
 9 8                        1   242   71262 0.281 
10 8                       NA    11    5223 0.0206
11 9                        0    60   12720 0.695 
12 9                        1     6    5576 0.305 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fig_inc_educacion</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): font family
not found in Windows font database</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los jóvenes egresados de técnico superior presentan el mayor porcentaje de sobrecalificados: 58.9%. Por su parte, los egresados de maestría presentan el menor porcentaje: 28.1%</p>
<p>Parece que conforme aumenta el nivel educativo del individuo disminuye el porcentaje de sobrecalificados.</p>
<p>Para ser exactos, creo que también se observa un comportamiento cóncavo hacia arriba. Se valida con <code>anios_estudios</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>inc_anios_est <span class="ot">&lt;-</span> <span class="fu">calcular_inc_svy_des</span>(datos_svy, anios_estudios, over_obj) <span class="sc">|&gt;</span> <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se realiza gráfica</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>inc_anios_est <span class="sc">|&gt;</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">over_obj =</span> <span class="fu">factor</span>(over_obj)) <span class="sc">|&gt;</span> </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> anios_estudios, <span class="at">y =</span> prop)) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#314763"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#314763"</span>) <span class="sc">+</span> </span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En efecto, en promedio disminuye la proporción de sobrecalificados conforme se incrementan los años de estudios de la muestra</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>df_3 <span class="ot">&lt;-</span> inc_anios_est <span class="sc">|&gt;</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>model_inc_anios_est <span class="ot">&lt;-</span> <span class="fu">lm</span>(prop <span class="sc">~</span> anios_estudios, <span class="at">data =</span> df_3)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(model_inc_anios_est)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prop ~ anios_estudios, data = df_3)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.12960 -0.06326 -0.00495  0.07692  0.19908 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)     1.11313    0.25490   4.367  0.00329 **
anios_estudios -0.04071    0.01482  -2.746  0.02867 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1148 on 7 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.5186,    Adjusted R-squared:  0.4498 
F-statistic:  7.54 on 1 and 7 DF,  p-value: 0.02867</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>model_inc_anios_est<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) anios_estudios 
    1.11312824    -0.04070593 </code></pre>
</div>
</div>
<p>En promedio, disminuye 4.1% el porcentaje de sobrecalificados cuando aumenta un año de educación, ceteris paribus.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.04070593</span> <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.070593</code></pre>
</div>
</div>
<p>¿Se puede valir por género? Quizá sí, pero sería sin la función</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>datos_svy <span class="sc">|&gt;</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(educacion, mujer, over_obj) <span class="sc">|&gt;</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot)) <span class="sc">|&gt;</span> </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  educacion mujer over_obj     tot  prop
  &lt;fct&gt;     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 6             0        1   21861 0.568
2 6             1        1   20244 0.614
3 7             0        1 1087357 0.538
4 7             1        1 1062688 0.508
5 8             0        1   37421 0.304
6 8             1        1   33841 0.258
7 9             1        1    5576 0.432</code></pre>
</div>
</div>
<p>Espero entender bien, cuando se analiza por género. En el caso de técnico superior, el 61.4% de las mujeres están sobrecalificadas comparado con el 56.8% de los hombres.</p>
<p>En licenciatura: 53.8% hombres y 50.8%</p>
<p>En maestría: 30.4% hombres y 25.8% mujeres</p>
<p>En doctorado: 0% hombres y 43.2% mujeres</p>
<p>Conforme aumenta el nivel educativo, disminuye el porcentaje de mujeres sobrecalificadas</p>
<p>POR CARRERAS</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_carreras <span class="sc">|&gt;</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 5
   campo_amplio edu_mismatch_obj     n    tot  prop
   &lt;fct&gt;                   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 10                          1   486 130017 0.888
 2 99                          1    37  11090 0.641
 3 04                          1  2273 669322 0.635
 4 08                          1   152  54215 0.623
 5 07                          1  1716 453177 0.568
 6 03                          1  1448 410916 0.520
 7 06                          1   437 141748 0.473
 8 05                          1   170  42116 0.384
 9 02                          1   241  67328 0.355
10 01                          1   484 152728 0.351
11 09                          1   527 136331 0.259</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>fig_inc_carreras</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
family not found in Windows font database</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
font family not found in Windows font database</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El 88.8% de jóvenes egresados de la carrera de servicios están sobrecalificados.</p>
<p>Este es un hallazgo impresionante. La literatura no ha mostrado algo al respecto de la carrera de servicios. La literatura ha identificado que las carreras relacionadas a ciencias sociales y economico administrativas presentaban la mayor incidencia. Parece que, como lo sospechaba, la literatura no consideró los estudios de técnico superior, es decir, a toda la educación superior. Solamente se enfocaban en los individuos con estudios profesionales (de licenciatura). ¿Cómo se puede validar?</p>
<p>Primero, validando la composición de la distribución por nivel educativo</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>datos_svy <span class="sc">|&gt;</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(campo_amplio <span class="sc">==</span> <span class="st">"10"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(campo_amplio, educacion) <span class="sc">|&gt;</span> </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot)) <span class="sc">|&gt;</span> </span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
# Groups:   campo_amplio [1]
  campo_amplio educacion    tot   prop
  &lt;fct&gt;        &lt;fct&gt;      &lt;dbl&gt;  &lt;dbl&gt;
1 10           7         133480 0.911 
2 10           6           9925 0.0678
3 10           8           3087 0.0211</code></pre>
</div>
</div>
<p>Del total de individuos egresados de la carrera de servicios, el 91.1% son egresados de los estudios de licenciatura.</p>
<p>Entonces, no. A pesar de que elimine los estudios de técnico superior, la carrera de servicios presentará la mayor incidencia. Se valida.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>datos_svy <span class="sc">|&gt;</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(campo_amplio <span class="sc">==</span> <span class="st">"10"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(campo_amplio, educacion, over_obj) <span class="sc">|&gt;</span> </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
# Groups:   campo_amplio, educacion [3]
  campo_amplio educacion over_obj    tot   prop
  &lt;fct&gt;        &lt;fct&gt;        &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 10           6                0   2536 0.256 
2 10           6                1   7389 0.744 
3 10           7                0  11070 0.0829
4 10           7                1 120830 0.905 
5 10           7               NA   1580 0.0118
6 10           8                0   1289 0.418 
7 10           8                1   1798 0.582 </code></pre>
</div>
</div>
<p>En efecto, del total de jóvenes egresados de la carrera de servicios los que tienen estudios de licenciatura, el 90.5% está sobrecalificado. Por su parte, los egresados de técnico superior el 74.4% lo está.</p>
<p>¿Qué campos específicos presentan mayor sobrecalificación?</p>
<p>Primero se añade dicha variable, se intenta directamente en <code>jovenes</code></p>
<pre><code>datos_procesados &lt;- datos_procesados %&gt;% 
    mutate(
      campo_amplio = if_else(str_length(cs_p14_c) == 5, str_c("0", cs_p14_c), cs_p14_c)
    ) %&gt;% 
    separate(
      campo_amplio,
      # campo amplio a 1 dígito de CMPE
      into = c("campo_amplio", "res"),
      sep = 2
    ) %&gt;% 
    select(-res)</code></pre>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>df_4 <span class="ot">&lt;-</span> jovenes <span class="sc">|&gt;</span> </span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">campo_espec =</span> <span class="fu">if_else</span>(<span class="fu">str_length</span>(cs_p14_c) <span class="sc">==</span> <span class="dv">5</span>, <span class="fu">str_c</span>(<span class="st">"0"</span>, cs_p14_c), cs_p14_c),</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">campo_detal =</span> <span class="fu">if_else</span>(<span class="fu">str_length</span>(cs_p14_c) <span class="sc">==</span> <span class="dv">5</span>, <span class="fu">str_c</span>(<span class="st">"0"</span>, cs_p14_c), cs_p14_c),</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    campo_espec,</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>      <span class="co"># campo específico a 2 dígitos de CMPE</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"campo_espec"</span>, <span class="st">"res"</span>),</span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">sep =</span> <span class="dv">3</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(</span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a>    campo_detal,</span>
<span id="cb85-14"><a href="#cb85-14" aria-hidden="true" tabindex="-1"></a>      <span class="co"># campo detallado a 3 dígitos de CMPE</span></span>
<span id="cb85-15"><a href="#cb85-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"campo_detal"</span>, <span class="st">"res"</span>),</span>
<span id="cb85-16"><a href="#cb85-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">sep =</span> <span class="dv">4</span></span>
<span id="cb85-17"><a href="#cb85-17" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb85-18"><a href="#cb85-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se calcula incidencia</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>df_6 <span class="ot">&lt;-</span> df_4 <span class="sc">|&gt;</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(campo_espec, over_obj) <span class="sc">|&gt;</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot)) <span class="sc">|&gt;</span> </span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(over_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'campo_espec'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>df_6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 29 × 4
   campo_espec over_obj    tot  prop
   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 101                1 120809 0.909
 2 104                1   3569 0.900
 3 081                1  44682 0.737
 4 102                1   5443 0.712
 5 042                1 384434 0.695
 6 999                1  11090 0.641
 7 071                1 346133 0.620
 8 041                1 284888 0.568
 9 031                1 170938 0.549
10 032                1  34433 0.523
# ℹ 19 more rows</code></pre>
</div>
</div>
<p>Los campos específicos que presentan mayor sobrecalificación son:</p>
<ul>
<li>101 servicios profesionales y deportes: 90.9%</li>
<li>104: servicios de seguridad: 90.0%</li>
<li>081: agronomía, horticultura, silvicultura y pesca: 73.7%</li>
</ul>
<p>Por su parte, las que presentan menor incidencia:</p>
<ul>
<li>091: ciencias médicas: 9.3%</li>
<li>103: seguridad para el trabajo: 10.2%</li>
<li>053 Matemáticas y estadística: 18.2%</li>
</ul>
<p>¿Cuántos están por encima de la incidencia general?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>df_5 <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>campo_espec, <span class="sc">~</span>over_obj, <span class="sc">~</span>tot, <span class="sc">~</span>prop,</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"general"</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">0.509449336</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>df_6 <span class="sc">|&gt;</span> </span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(df_5) <span class="sc">|&gt;</span> </span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prop <span class="sc">&gt;=</span> prop[campo_espec <span class="sc">==</span> <span class="st">"general"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 4
   campo_espec over_obj    tot  prop
   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 101                1 120809 0.909
 2 104                1   3569 0.900
 3 081                1  44682 0.737
 4 102                1   5443 0.712
 5 042                1 384434 0.695
 6 999                1  11090 0.641
 7 071                1 346133 0.620
 8 041                1 284888 0.568
 9 031                1 170938 0.549
10 032                1  34433 0.523
11 072                1  25965 0.512
12 062                1  40685 0.510
13 general            1      1 0.509</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>df_6 <span class="sc">|&gt;</span> </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(df_5) <span class="sc">|&gt;</span> </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prop <span class="sc">&lt;=</span> prop[campo_espec <span class="sc">==</span> <span class="st">"general"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 4
   campo_espec over_obj    tot   prop
   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 033                1 205545 0.497 
 2 095                1  14455 0.464 
 3 061                1 101063 0.460 
 4 051                1  28310 0.438 
 5 011                1  92276 0.435 
 6 073                1  81079 0.430 
 7 052                1  10309 0.401 
 8 094                1  44367 0.387 
 9 021                1  53191 0.365 
10 082                1   9533 0.361 
11 022                1  14137 0.323 
12 012                1  60452 0.271 
13 092                1  54580 0.269 
14 093                1  11539 0.211 
15 053                1   3497 0.182 
16 103                1    196 0.102 
17 091                1  11390 0.0931
18 general            1      1 0.509 </code></pre>
</div>
</div>
<p>12 carreras son superior a la incidencia general.</p>
<p>Mientras que 17 son menores a la incidencia general</p>
<p>Por último,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>df_4 <span class="sc">|&gt;</span> </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(campo_espec, over_obj, campo_detal) <span class="sc">|&gt;</span> </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> tot <span class="sc">/</span> <span class="fu">sum</span>(tot)) <span class="sc">|&gt;</span> </span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop), <span class="at">.by_group =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'campo_espec', 'over_obj'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 278 × 5
# Groups:   campo_espec, over_obj [83]
   campo_espec over_obj campo_detal   tot    prop
   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;
 1 011                0 0115        63455 0.543  
 2 011                0 0111        43944 0.376  
 3 011                0 0113         5229 0.0448 
 4 011                0 0112         2507 0.0215 
 5 011                0 0110         1272 0.0109 
 6 011                0 0114          387 0.00331
 7 011                1 0111        50747 0.550  
 8 011                1 0115        34976 0.379  
 9 011                1 0112         2821 0.0306 
10 011                1 0113         2627 0.0285 
# ℹ 268 more rows</code></pre>
</div>
</div>
<p>Del total de sobrecalificados:</p>
<p>De las carreras con mayor sobrecalificación:</p>
<p>101</p>
<ul>
<li>El 57.0% son de 1015 gastronomía y servicios</li>
<li>25.9% de 1016 Hospitalidad y turismo</li>
<li>15.0% de 1013 Servicios de cuidado personal y belleza</li>
</ul>
<p>104</p>
<ul>
<li>96.6% de 1041 Seguridad pública</li>
</ul>
<p>081</p>
<ul>
<li>89.8% de 0811 Producción y explotación agrícola y ganadera</li>
</ul>
<p>Del total sin sobrecalificación:</p>
<p>De las carreras con menor sobrecalificación:</p>
<p>091</p>
<ul>
<li>84.2% de 0911 Medicina general</li>
</ul>
<p>053</p>
<ul>
<li>55.0% de 0531 Matemáticas</li>
<li>45.0% de 0532 Estadística y actuaría</li>
</ul>
<p>Si Salas Velasco menciona que las carreras de habilidades específicas presentan menor probabilidad de desajuste vertical y horizontal, ¿por qué las carreras de servicios presentan la mayor incidencia?</p>
<p>POR REGIONES</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_regiones <span class="sc">|&gt;</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
# Groups:   regiones [5]
  regiones edu_mismatch_obj     n    tot  prop
  &lt;fct&gt;               &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 1                       1  2218 440504 0.599
2 2                       1  1782 850699 0.462
3 3                       1   998 315001 0.502
4 4                       1  1698 467714 0.514
5 5                       1  1275 195070 0.578</code></pre>
</div>
</div>
<p>Me percate que tenía asignado incorrectamente los valores que identifica cada región del país</p>
<p>El cambio se hace en “C:/Prog/tesis/scripts/3_construccion_variables_v2.R” y se guardan en “C:/Prog/tesis/scripts/3_construccion_variables_v3.R”. Asimismo, se modifica “C:/Prog/tesis/scripts/6_cuadros_v3.R” el cambio de archivo. Se vuelve a ejecutar todo el código de este archivo</p>
<p>Después de aplicar los cambios. Se observa que la región sur presenta la mayor incidencia: 59.9%. Mientras que la región centro la menor incidencia: 46.2%.</p>
<p>POR ESTADOS</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_estados <span class="sc">|&gt;</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(prop))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 5
# Groups:   ent [32]
   ent   edu_mismatch_obj     n    tot  prop
   &lt;chr&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 12                   1   163  41318 0.637
 2 27                   1   266  44468 0.620
 3 23                   1   238  48014 0.618
 4 18                   1   296  26647 0.616
 5 30                   1   309 117148 0.611
 6 25                   1   305  90695 0.608
 7 17                   1   200  41958 0.605
 8 16                   1   212  87706 0.601
 9 28                   1   327  77029 0.594
10 29                   1   205  27712 0.591
# ℹ 22 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>fig_inc_estados</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
family not found in Windows font database</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los estados que presentan mayor incidencia:</p>
<ul>
<li>12 Guerrero: 63.7%</li>
<li>27 Tabasco: 62.0%</li>
<li>23 Quintana Roo: 61.8%</li>
</ul>
<p>Por su parte, los que presentan menor incidencia:</p>
<ul>
<li>9 CDMX: 36.8%</li>
<li>22 Querétaro: 43.6%</li>
<li>19 Nuevo Léon: 44.7%</li>
</ul>
<p>¿Cuántos están por encima o por debajo de la incidencia general?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>df_7 <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>ent, <span class="sc">~</span>edu_mismatch_obj, <span class="sc">~</span>n, <span class="sc">~</span>tot, <span class="sc">~</span>prop,</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"general"</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">0.509449336</span></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>tbl_inc_estados <span class="sc">|&gt;</span> </span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(df_7) <span class="sc">|&gt;</span> </span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prop <span class="sc">&gt;=</span> prop[ent <span class="sc">==</span> <span class="st">"general"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 5
   ent   edu_mismatch_obj     n   tot  prop
   &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 10                   1   259 34874 0.530
 2 11                   1   222 89155 0.546
 3 12                   1   163 41318 0.637
 4 13                   1   204 46642 0.569
 5 16                   1   212 87706 0.601
 6 17                   1   200 41958 0.605
 7 18                   1   296 26647 0.616
 8 2                    1   290 71615 0.548
 9 20                   1   221 50843 0.580
10 21                   1   257 94780 0.512
# ℹ 14 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>tbl_inc_estados <span class="sc">|&gt;</span> </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(df_7) <span class="sc">|&gt;</span> </span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prop <span class="sc">&lt;=</span> prop[ent <span class="sc">==</span> <span class="st">"general"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   ent     edu_mismatch_obj     n    tot  prop
   &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 1                      1   193  28429 0.467
 2 14                     1   215 143075 0.470
 3 15                     1   279 306218 0.468
 4 19                     1   219 112543 0.447
 5 22                     1   235  50144 0.436
 6 24                     1   174  41667 0.487
 7 5                      1   335  66240 0.499
 8 6                      1   204  14124 0.456
 9 9                      1   180 194090 0.368
10 general                1     1      1 0.509</code></pre>
</div>
</div>
<p>23 estados tienen una incidencia mayor a la general y 9 por debajo</p>
<p>Parece existir una relación entre las condiciones laborales precarias y la sobrecalificación por entidad federativa, pero ¿cómo validarlo?</p>
<ul>
<li>Tasa de condiciones críticas de ocupación TCCO</li>
<li>Tasa de informalidad laboral 1 TIL1</li>
</ul>
<p>Pero, ¿qué es TCCO?</p>
<p>Se investigo en internet: https://www.inegi.org.mx/contenidos/saladeprensa/boletines/2026/iooe/IOE2026_01.pdf p.&nbsp;9</p>
<p>Además, de las tasa mencionadas existen:</p>
<ul>
<li>Tasa de presión general</li>
<li>Tasa de subocupación</li>
</ul>
<p>A continuación, se definen</p>
<p>Tasa de presión general:</p>
<p>“… la tasa es una medida global de la competencia por plazas de trabajo que se conforma por quienes quieren trabajar; por quienes tienen un empleo, pero quieren cambiarlo; y por quienes buscan otro más para tener un segundo trabajo.”</p>
<p>Tasa de subocupación:</p>
<p>“Constituye a la población ocupada que tiene la necesidad y disponibilidad de ofertar más tiempo de trabajo de lo que su ocupación actual le permite.”</p>
<p>Tasa de condiciones críticas de ocupación:</p>
<p>“Indicador de condiciones inadecuadas de empleo desde el punto de vista del tiempo de trabajo, los ingresos o una combinación insatisfactoria de ambos. Incluye a las personas que trabajan menos de 35 horas a la semana por razones ajenas a sus decisiones, a quienes trabajan más de 35 horas semanales con ingresos mensuales inferiores al salario mínimo y a quienes laboran más de 48 horas semanales y que ganan hasta dos salarios mínimos”</p>
<p>Tasa de informalidad laboral 1:</p>
<p>“Se refiere a la suma, sin duplicar, de las y los ocupados que son laboralmente vulnerables por la naturaleza de la unidad económica para la que trabajan, más aquellas personas cuyo vínculo o dependencia laboral no se reconoce por su fuente de trabajo. En esta tasa se incluyen —además del componente que labora en micronegocios no registrados o sector informal— otras modalidades análogas, como las y los ocupados por cuenta propia en la agricultura de subsistencia, así como a quienes laboran sin la protección de la seguridad social y cuyos servicios los utilizan las unidades económicas registradas”</p>
<p>Es decir,</p>
<ul>
<li>TPG: refiere competencia por puestos de trabajo</li>
<li>TSUB: indica cuántas personas quieren trabajar más tiempo</li>
<li>TCCO: condición del trabajo medido en tiempo de trabajo e ingreso percibido</li>
<li>TIL1: trabajadores vulnerables o que la empresa no los reconoce como tal</li>
</ul>
<p>Me interesa TCCO y TIL1, establezco que las características de la ocupación se relacionan con la sobrecalificación, es decir, en los estados donde existe una mayor tasa crítica de ocupación hay mayor incidencia y viceversa.</p>
<p>Vamos a empezar con TCCO</p>
<p>De acuerdo a (INEGI, 2023) se calcula así</p>
<p><span class="math display">\[
TCCO = PCCO / PO * 100
\]</span></p>
<p>Donde</p>
<p><span class="math inline">\(PCCO\)</span>: Población en Condiciones Críticas de Ocupación (TCCO=1 a 3)</p>
<p><span class="math inline">\(PO\)</span>: Población Ocupada (Clase2=1)</p>
<p>Primero, vamos a calcular la tasa general para lo cual ocuparemos la tabla <code>ocupada</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(tcco) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  tcco       n
  &lt;chr&gt;  &lt;int&gt;
1 0     131634
2 1        360
3 2      41849
4 3      16844</code></pre>
</div>
</div>
<p>Entonces, se seleccionan los valores distintos a 0.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(clase2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  clase2      n
  &lt;chr&gt;   &lt;int&gt;
1 1      190687</code></pre>
</div>
</div>
<p>Se me ocurre a partir de aplicar filtro en <code>summarise</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fac_tri =</span> <span class="fu">as.double</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pcco =</span> <span class="fu">sum</span>(fac_tri[tcco <span class="sc">!=</span> <span class="st">"0"</span>]),</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">po =</span> <span class="fu">sum</span>(fac_tri),</span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">tcco =</span> pcco <span class="sc">/</span> po </span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
      pcco       po  tcco
     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1 19164131 59440760 0.322</code></pre>
</div>
</div>
<p>Se valida con “https://www.inegi.org.mx/contenidos/saladeprensa/boletines/2025/enoe/enoe2025_08.pdf”</p>
<p>Los resultados se aproximan mucho. En el informe aparece una tasa de 32.5% y aquí de 32.2%</p>
<p>Ahora se procede a crear la función</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>calcular_tcco <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, ponderador){</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  datos <span class="sc">|&gt;</span> </span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pcco =</span> <span class="fu">sum</span>({{ ponderador }}[tcco <span class="sc">!=</span> <span class="st">"0"</span>]),</span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">po =</span> <span class="fu">sum</span>({{ ponderador }}),</span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">tcco =</span> pcco <span class="sc">/</span> po </span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fac_tri =</span> <span class="fu">as.double</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calcular_tcco</span>(fac_tri)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
      pcco       po  tcco
     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1 19164131 59440760 0.322</code></pre>
</div>
</div>
<p>Ahora se hace a nivel estatal</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fac_tri =</span> <span class="fu">as.double</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ent) <span class="sc">|&gt;</span> </span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pcco =</span> <span class="fu">sum</span>(fac_tri[tcco <span class="sc">!=</span> <span class="st">"0"</span>]),</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">po =</span> <span class="fu">sum</span>(fac_tri),</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">tcco =</span> pcco <span class="sc">/</span> po</span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 4
   ent      pcco      po  tcco
   &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 1      142276  652132 0.218
 2 10     283681  860551 0.330
 3 11    1014042 2850322 0.356
 4 12     495084 1507245 0.328
 5 13     461209 1457012 0.317
 6 14     653556 3874934 0.169
 7 15    3407651 8152117 0.418
 8 16     743940 2258881 0.329
 9 17     236831  845616 0.280
10 18     162355  619858 0.262
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>Está correcto!!</p>
<p>Ahora se unen</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>tcco_estados <span class="ot">&lt;-</span> ocupada <span class="sc">|&gt;</span> </span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fac_tri =</span> <span class="fu">as.double</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ent) <span class="sc">|&gt;</span> </span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pcco =</span> <span class="fu">sum</span>(fac_tri[tcco <span class="sc">!=</span> <span class="st">"0"</span>]),</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">po =</span> <span class="fu">sum</span>(fac_tri),</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">tcco =</span> pcco <span class="sc">/</span> po</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida tipos de datos en <code>tbl_inc_estados</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tbl_inc_estados)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 110
Columns: 5
Groups: ent [32]
$ ent              &lt;chr&gt; "1", "1", "1", "1", "10", "10", "10", "11", "11", "11…
$ edu_mismatch_obj &lt;dbl&gt; 0, 1, 2, NA, 0, 1, NA, 0, 1, NA, 0, 1, NA, 0, 1, 2, N…
$ n                &lt;int&gt; 215, 193, 1, 8, 240, 259, 4, 202, 222, 4, 103, 163, 4…
$ tot              &lt;dbl&gt; 31264, 28429, 167, 1005, 30081, 34874, 842, 73287, 89…
$ prop             &lt;dbl&gt; 0.513661382, 0.467082888, 0.002743777, 0.016511953, 0…</code></pre>
</div>
</div>
<p>Se unen</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>tcco_estados_over <span class="ot">&lt;-</span> tbl_inc_estados <span class="sc">|&gt;</span> </span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(tcco_estados, <span class="at">by =</span> <span class="st">"ent"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se grafica</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>tcco_estados_over <span class="sc">|&gt;</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tcco, prop)) <span class="sc">+</span> </span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> ent))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Sin establecer ningún tipo de relación, a priori, establecido por defecto en <code>geom_smooth</code>. Se observa un comportamiento casi lineal.</p>
<p>Se calcula coeficiente de correlación</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">cor</span>(tcco_estados_over<span class="sc">$</span>tcco, tcco_estados_over<span class="sc">$</span>prop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3822627</code></pre>
</div>
</div>
<p>Es del 38.2%, que indica una relación positiva</p>
<p>Ahora vayamos con las demás tasas. Me interesa la tasa de informalidad 1. Se calcula así</p>
<p><span class="math display">\[
TIL1 = POI / PO
\]</span></p>
<p>Donde</p>
<p><span class="math inline">\(PO\)</span>: población en Ocupación Informal (EMP_PPAL=1)</p>
<p><span class="math inline">\(PO\)</span>: Población Ocupada (Clase2=1)</p>
<p>Se calcula TIL1 general</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>ocupada <span class="sc">|&gt;</span> </span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fac_tri =</span> <span class="fu">as.double</span>(fac_tri)) <span class="sc">|&gt;</span> </span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">poi =</span> <span class="fu">sum</span>(fac_tri[emp_ppal <span class="sc">==</span> <span class="st">"1"</span>]),</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">po =</span> <span class="fu">sum</span>(fac_tri),</span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">til1 =</span> poi <span class="sc">/</span> po</span>
<span id="cb126-7"><a href="#cb126-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
       poi       po  til1
     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1 32589068 59440760 0.548</code></pre>
</div>
</div>
<p>Está correcto</p>
<p>Se calcula a nivel estatal</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># solo para TIL1</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>calcular_til1_estados <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, grupo, ponderador){</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>  datos <span class="sc">|&gt;</span> </span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ponderador =</span> <span class="fu">as.double</span>({{ ponderador }})) <span class="sc">|&gt;</span> </span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>({{ grupo }}) <span class="sc">|&gt;</span> </span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">poi =</span> <span class="fu">sum</span>(ponderador[emp_ppal <span class="sc">==</span> <span class="st">"1"</span>]),</span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">po =</span> <span class="fu">sum</span>(ponderador),</span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">til1 =</span> poi <span class="sc">/</span> po</span>
<span id="cb128-10"><a href="#cb128-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb128-11"><a href="#cb128-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb128-12"><a href="#cb128-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-13"><a href="#cb128-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener tasa en general</span></span>
<span id="cb128-14"><a href="#cb128-14" aria-hidden="true" tabindex="-1"></a>calcular_t_ocup_gpo <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, grupo, ponderador, poblacion, condicion, valor){</span>
<span id="cb128-15"><a href="#cb128-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># concateno</span></span>
<span id="cb128-16"><a href="#cb128-16" aria-hidden="true" tabindex="-1"></a>  filtro <span class="ot">&lt;-</span> <span class="fu">paste</span>(poblacion, condicion, valor)</span>
<span id="cb128-17"><a href="#cb128-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb128-18"><a href="#cb128-18" aria-hidden="true" tabindex="-1"></a>  datos <span class="sc">|&gt;</span> </span>
<span id="cb128-19"><a href="#cb128-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ponderador =</span> <span class="fu">as.double</span>({{ ponderador }})) <span class="sc">|&gt;</span> </span>
<span id="cb128-20"><a href="#cb128-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>({{ grupo }}) <span class="sc">|&gt;</span> </span>
<span id="cb128-21"><a href="#cb128-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb128-22"><a href="#cb128-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">numerador =</span> <span class="fu">sum</span>(ponderador[ <span class="sc">!!</span><span class="fu">parse_expr</span>(filtro) ]),</span>
<span id="cb128-23"><a href="#cb128-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">denominador =</span> <span class="fu">sum</span>(ponderador),</span>
<span id="cb128-24"><a href="#cb128-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">tasa =</span> numerador <span class="sc">/</span> denominador</span>
<span id="cb128-25"><a href="#cb128-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb128-26"><a href="#cb128-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb128-27"><a href="#cb128-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-28"><a href="#cb128-28" aria-hidden="true" tabindex="-1"></a>crear_fig_tasa_vs_over <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, grupo, tasa, prop){</span>
<span id="cb128-29"><a href="#cb128-29" aria-hidden="true" tabindex="-1"></a>  datos <span class="sc">|&gt;</span> </span>
<span id="cb128-30"><a href="#cb128-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>({{ tasa }}, {{ prop }})) <span class="sc">+</span> </span>
<span id="cb128-31"><a href="#cb128-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb128-32"><a href="#cb128-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb128-33"><a href="#cb128-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> {{ grupo }}))</span>
<span id="cb128-34"><a href="#cb128-34" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida</p>
<p>TIL1</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>til1_estados <span class="ot">&lt;-</span> <span class="fu">calcular_t_ocup_gpo</span>(ocupada, ent, fac_tri, <span class="st">"emp_ppal"</span>, <span class="st">"=="</span>, <span class="st">"1"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sí se pudo!!!</p>
<p>Se une</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>til1_estados_over <span class="ot">&lt;-</span> tbl_inc_estados <span class="sc">|&gt;</span> </span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(til1_estados, <span class="at">by =</span> <span class="st">"ent"</span>)</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a><span class="fu">crear_fig_tasa_vs_over</span>(til1_estados_over, ent, tasa, prop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29_C3_V3_acopio_v2_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Existe una mejor relación</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">cor</span>(til1_estados_over<span class="sc">$</span>tasa, til1_estados_over<span class="sc">$</span>prop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5515643</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>unir_tbl_tasa_over <span class="ot">&lt;-</span> <span class="cf">function</span>(datos1, datos2, llave){</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>  datos1 <span class="sc">|&gt;</span> </span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(edu_mismatch_obj <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(datos2, <span class="at">by =</span> <span class="fu">join_by</span>({{  llave  }}))</span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unir_tbl_tasa_over</span>(tbl_inc_estados, til1_estados, ent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 8
# Groups:   ent [32]
   ent   edu_mismatch_obj     n    tot  prop numerador denominador  tasa
   &lt;chr&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 1                    1   193  28429 0.467    273102      652132 0.419
 2 10                   1   259  34874 0.530    440602      860551 0.512
 3 11                   1   222  89155 0.546   1558997     2850322 0.547
 4 12                   1   163  41318 0.637   1146195     1507245 0.760
 5 13                   1   204  46642 0.569   1031145     1457012 0.708
 6 14                   1   215 143075 0.470   1754979     3874934 0.453
 7 15                   1   279 306218 0.468   4553459     8152117 0.559
 8 16                   1   212  87706 0.601   1570417     2258881 0.695
 9 17                   1   200  41958 0.605    548809      845616 0.649
10 18                   1   296  26647 0.616    370417      619858 0.598
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>De momento me quedo con las dos tasas calculadas:</p>
<ul>
<li>TCCO</li>
<li>TIL1</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>tcco_estados_over</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 8
# Groups:   ent [32]
   ent   edu_mismatch_obj     n    tot  prop    pcco      po  tcco
   &lt;chr&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 1                    1   193  28429 0.467  142276  652132 0.218
 2 10                   1   259  34874 0.530  283681  860551 0.330
 3 11                   1   222  89155 0.546 1014042 2850322 0.356
 4 12                   1   163  41318 0.637  495084 1507245 0.328
 5 13                   1   204  46642 0.569  461209 1457012 0.317
 6 14                   1   215 143075 0.470  653556 3874934 0.169
 7 15                   1   279 306218 0.468 3407651 8152117 0.418
 8 16                   1   212  87706 0.601  743940 2258881 0.329
 9 17                   1   200  41958 0.605  236831  845616 0.280
10 18                   1   296  26647 0.616  162355  619858 0.262
# ℹ 22 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>til1_estados_over</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 8
# Groups:   ent [32]
   ent   edu_mismatch_obj     n    tot  prop numerador denominador  tasa
   &lt;chr&gt;            &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;
 1 1                    1   193  28429 0.467    273102      652132 0.419
 2 10                   1   259  34874 0.530    440602      860551 0.512
 3 11                   1   222  89155 0.546   1558997     2850322 0.547
 4 12                   1   163  41318 0.637   1146195     1507245 0.760
 5 13                   1   204  46642 0.569   1031145     1457012 0.708
 6 14                   1   215 143075 0.470   1754979     3874934 0.453
 7 15                   1   279 306218 0.468   4553459     8152117 0.559
 8 16                   1   212  87706 0.601   1570417     2258881 0.695
 9 17                   1   200  41958 0.605    548809      845616 0.649
10 18                   1   296  26647 0.616    370417      619858 0.598
# ℹ 22 more rows</code></pre>
</div>
</div>
<p>Por último, vamos a realizar una regresión múltiple con dichas tasas</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>estados_tasas_over <span class="ot">&lt;-</span> tcco_estados_over <span class="sc">|&gt;</span> </span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(til1_estados_over, <span class="at">by =</span> <span class="st">"ent"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ent, prop.x, tcco, tasa) <span class="sc">|&gt;</span> </span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"over"</span> <span class="ot">=</span> <span class="st">"prop.x"</span>,</span>
<span id="cb141-6"><a href="#cb141-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"til1"</span> <span class="ot">=</span> <span class="st">"tasa"</span></span>
<span id="cb141-7"><a href="#cb141-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb141-8"><a href="#cb141-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb141-9"><a href="#cb141-9" aria-hidden="true" tabindex="-1"></a>model_estados_t_over <span class="ot">&lt;-</span> <span class="fu">lm</span>(over <span class="sc">~</span> tcco <span class="sc">+</span> til1, <span class="at">data =</span> estados_tasas_over)</span>
<span id="cb141-10"><a href="#cb141-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb141-11"><a href="#cb141-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(model_estados_t_over)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = over ~ tcco + til1, data = estados_tasas_over)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.146478 -0.038365  0.000848  0.040430  0.101513 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.39163    0.04690   8.350 3.33e-09 ***
tcco         0.05372    0.17432   0.308   0.7602    
til1         0.24448    0.09441   2.590   0.0149 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.057 on 29 degrees of freedom
Multiple R-squared:  0.3065,    Adjusted R-squared:  0.2587 
F-statistic: 6.408 on 2 and 29 DF,  p-value: 0.004957</code></pre>
</div>
</div>
<p>TCCO no es significativa!!! Se elimina del modelo y se vuelve a estimar</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>model_estados_t_over <span class="ot">&lt;-</span> <span class="fu">lm</span>(over <span class="sc">~</span> til1, <span class="at">data =</span> estados_tasas_over)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(model_estados_t_over)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = over ~ til1, data = estados_tasas_over)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.145815 -0.040522  0.003539  0.037131  0.104217 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.39830    0.04097   9.722 8.78e-11 ***
til1         0.26268    0.07253   3.622  0.00107 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05613 on 30 degrees of freedom
Multiple R-squared:  0.3042,    Adjusted R-squared:  0.281 
F-statistic: 13.12 on 1 and 30 DF,  p-value: 0.001067</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>model_estados_t_over<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        til1 
  0.3982993   0.2626835 </code></pre>
</div>
</div>
<p>El modelo explica el 30.4% de la variabilidad de los datos (R-Cuadrada).</p>
<p>Por otra parte, el coeficiente tiene un nivel de confianza del 99%, siendo estadísticamente significativo.</p>
<p>Indica que, un aumento del 1% de la tasa de informalidad laboral 1 (TIL1) incrementa, en promedio, el porcentaje de sobrecalificación un 26.3% de jóvenes egresados en el estado <span class="math inline">\(i\)</span></p>
<p>Se validan valores predichos</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>model_estados_t_over<span class="sc">$</span>fitted.values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
0.5083067 0.5327932 0.5419752 0.5980588 0.5842035 0.5172701 0.5450242 0.5809218 
        9        10        11        12        13        14        15        16 
0.5687822 0.5552746 0.4868087 0.4991390 0.6045950 0.5850144 0.5088995 0.5136677 
       17        18        19        20        21        22        23        24 
0.5471515 0.5206029 0.5131062 0.5741671 0.5202852 0.5878968 0.4964541 0.5823687 
       25        26        27        28        29        30        31        32 
0.5523489 0.5528836 0.5554170 0.4881554 0.5249171 0.6030978 0.4884547 0.5141676 </code></pre>
</div>
</div>
<p>Parece que, la incidencia de la sobrecalificación a nivel estatal está relacionado a la estructura del mercado laboral de dicho estado. En estados caracterizados por mayor vulnerabilidad de los trabajadores presentan los mayores niveles de incidencia de sobrecalificación.</p>
<p>En ese sentido,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a>datos_svy <span class="sc">|&gt;</span> </span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calcular_inc_svy_des</span>(informal, over_obj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   informal [2]
  informal over_obj     n     tot   prop
  &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 0               0  5440 1701679 0.524 
2 0               1  5326 1508085 0.464 
3 0              NA   154   37784 0.0116
4 1               0  1523  429735 0.356 
5 1               1  2645  760903 0.631 
6 1              NA    50   15619 0.0129</code></pre>
</div>
</div>
<p>Los jóvenes ubicados en la informalidad presentan mayor incidencia: 63.1% comparado con 46.4% aquellos que no lo están.</p>
<p>Por último,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>datos_svy <span class="sc">|&gt;</span> </span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ingreso_mensual)) <span class="sc">|&gt;</span> </span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(edu_mismatch_obj) <span class="sc">|&gt;</span> </span>
<span id="cb151-4"><a href="#cb151-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">promedio =</span> <span class="fu">survey_mean</span>(ingreso_mensual))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  edu_mismatch_obj promedio promedio_se
             &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
1                0   18318.        468.
2                1   12984.        244.
3                2   15813.       3710.
4               NA   16223.       1536.</code></pre>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>