<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-08">

<title>c3_v3_acopio_reg</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="29_C3_V3_acopio_reg_files/libs/clipboard/clipboard.min.js"></script>
<script src="29_C3_V3_acopio_reg_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="29_C3_V3_acopio_reg_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="29_C3_V3_acopio_reg_files/libs/quarto-html/popper.min.js"></script>
<script src="29_C3_V3_acopio_reg_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="29_C3_V3_acopio_reg_files/libs/quarto-html/anchor.min.js"></script>
<link href="29_C3_V3_acopio_reg_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="29_C3_V3_acopio_reg_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="29_C3_V3_acopio_reg_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="29_C3_V3_acopio_reg_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="29_C3_V3_acopio_reg_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Este documento tiene como objetivo servir de apoyo para la redacción de la versión 3 del capítulo 3 Resultados.</p>
<p>Cabe señalar que a partir de “C:/Prog/tesis/29_C3_V3_acopio_v2.qmd”, se añadió esto</p>
<pre><code>mutate(
    campo_espec = if_else(str_length(cs_p14_c) == 5, str_c("0", cs_p14_c), cs_p14_c),
    campo_detal = if_else(str_length(cs_p14_c) == 5, str_c("0", cs_p14_c), cs_p14_c),
    ) %&gt;% 
  separate(
    campo_espec,
      # campo específico a 2 dígitos de CMPE
      into = c("campo_espec", "res"),
      sep = 3
    ) %&gt;% 
  separate(
    campo_detal,
      # campo detallado a 3 dígitos de CMPE
      into = c("campo_detal", "res"),
      sep = 4
    ) %&gt;%</code></pre>
<p>Al archivo “C:/Prog/tesis/scripts/3_construccion_variables_v3.R” y se guardo en “C:/Prog/tesis/scripts/3_construccion_variables_v4.R”</p>
<p>Para la regresión se trabajará con el modelo especificado en “C:/Prog/tesis/25_apoyo_c2_v3-3_muestra2.qmd”</p>
<pre><code>model_jov_svy &lt;- svyglm(
  log(ingreso_mensual) ~ 
    educacion + over_obj + under_obj + exper + I(exper**2) + 
    log(horas_lab) + mujer + casada + jefe_hogar + regiones + campo_amplio +
    division + pos_ocu + sector_eco + tamanio + informal + 
    jornada + unidad_eco, 
  design = jovenes_svy
)</code></pre>
<p>Para la regresión se trabará con los siguientes archivos</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/1_importacion_v12.R"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/2_construccion_tablas_v14.R"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/3_construccion_variables_v4.R"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"scripts/4_metodologia_v1.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Primero se definirá la tabla a ocupar</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>general <span class="ot">&lt;-</span> <span class="fu">construir_variables</span>(ocupada)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>general <span class="ot">&lt;-</span> <span class="fu">asignar_edu_mismatch</span>(general, ciuo08)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>general <span class="ot">&lt;-</span> <span class="fu">convertir_a_factor</span>(general)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>general_svy <span class="ot">&lt;-</span> <span class="fu">definir_encuesta</span>(general)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>jovenes_svy <span class="ot">&lt;-</span> <span class="fu">seleccionar_jov</span>(general_svy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida el tamaño de la muestra</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>jovenes_svy <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      n     tot
  &lt;int&gt;   &lt;dbl&gt;
1 15138 4453805</code></pre>
</div>
</div>
<p>Es correcto. Ahora se define la tabla para la regresión</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>jovenes_svy_reg <span class="ot">&lt;-</span> <span class="fu">seleccionar_obs_reg</span>(jovenes_svy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se valida el tamaño de la muestra</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>jovenes_svy_reg <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">tot =</span> <span class="fu">sum</span>(fac_tri)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      n     tot
  &lt;int&gt;   &lt;dbl&gt;
1  7708 1999466</code></pre>
</div>
</div>
<p>Se realiza la regresión general</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_gral <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    educacion <span class="sc">+</span> over_obj <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> mujer <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> regiones <span class="sc">+</span> campo_amplio <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> informal <span class="sc">+</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sí están todas las variables especificadas en el capítulo 2 versión 3-4 p.&nbsp;24</p>
<p>Se muestran los resultados</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_gral)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj + 
    under_obj + exper + I(exper^2) + log(horas_lab) + mujer + 
    casada + jefe_hogar + regiones + campo_amplio + division + 
    pos_ocu + sector_eco + tamanio + informal + jornada + unidad_eco, 
    design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     8.3196920  0.2044845  40.686  &lt; 2e-16 ***
educacion7      0.1255023  0.0662600   1.894 0.058267 .  
educacion8      0.2796181  0.0825980   3.385 0.000716 ***
educacion9      0.3090649  0.1338494   2.309 0.020979 *  
over_obj       -0.1920406  0.0305920  -6.277 3.71e-10 ***
under_obj       0.0876670  0.1064849   0.823 0.410385    
exper           0.0603579  0.0158608   3.805 0.000143 ***
I(exper^2)     -0.0034309  0.0010869  -3.157 0.001605 ** 
log(horas_lab)  0.1128129  0.0629867   1.791 0.073341 .  
mujer          -0.1054234  0.0214169  -4.922 8.81e-07 ***
casada          0.0362225  0.0236570   1.531 0.125790    
jefe_hogar      0.1246374  0.0220693   5.648 1.71e-08 ***
regiones2       0.1211339  0.0308804   3.923 8.87e-05 ***
regiones3       0.0512817  0.0289793   1.770 0.076851 .  
regiones4       0.2151976  0.0256978   8.374  &lt; 2e-16 ***
regiones5       0.0772714  0.0272650   2.834 0.004613 ** 
campo_amplio02  0.0633597  0.0510464   1.241 0.214580    
campo_amplio03  0.0662963  0.0363281   1.825 0.068068 .  
campo_amplio04  0.1193075  0.0340303   3.506 0.000459 ***
campo_amplio05  0.0338417  0.0786625   0.430 0.667058    
campo_amplio06  0.1163712  0.0548168   2.123 0.033807 *  
campo_amplio07  0.1374800  0.0368157   3.734 0.000190 ***
campo_amplio08  0.0799586  0.1031554   0.775 0.438299    
campo_amplio09  0.0924077  0.0380309   2.430 0.015140 *  
campo_amplio10  0.0804543  0.0457362   1.759 0.078619 .  
campo_amplio99  0.2247566  0.1036766   2.168 0.030213 *  
division2      -0.0883098  0.0442309  -1.997 0.045923 *  
division3      -0.2007216  0.0523422  -3.835 0.000127 ***
division4      -0.2887672  0.0545667  -5.292 1.26e-07 ***
division5      -0.1902401  0.0583419  -3.261 0.001118 ** 
division6      -0.3654821  0.1563910  -2.337 0.019477 *  
division7      -0.1668219  0.0778285  -2.143 0.032122 *  
division8      -0.3316900  0.0605442  -5.478 4.49e-08 ***
division9      -0.4095882  0.0718437  -5.701 1.25e-08 ***
pos_ocu2        0.4375974  0.0610381   7.169 8.57e-13 ***
pos_ocu3        0.0861220  0.0488330   1.764 0.077857 .  
sector_eco2    -0.0921806  0.0732314  -1.259 0.208173    
sector_eco3    -0.0328159  0.0709363  -0.463 0.643662    
sector_eco4    -0.1442919  0.1861406  -0.775 0.438270    
tamanio4        0.0943275  0.0345871   2.727 0.006408 ** 
tamanio5        0.1467223  0.0396247   3.703 0.000215 ***
tamanio6        0.2805928  0.0460204   6.097 1.16e-09 ***
tamanio7        0.3691386  0.0545799   6.763 1.49e-11 ***
tamanio8        0.0008073  0.0422119   0.019 0.984743    
informal1      -0.3074100  0.0259223 -11.859  &lt; 2e-16 ***
jornada3        0.4726507  0.0986507   4.791 1.70e-06 ***
jornada4        0.5005875  0.1228151   4.076 4.65e-05 ***
jornada5        0.4899056  0.1394075   3.514 0.000445 ***
unidad_eco2    -0.1853506  0.0344211  -5.385 7.56e-08 ***
unidad_eco3    -0.1203393  0.0455922  -2.639 0.008328 ** 
unidad_eco4    -0.0085580  0.1353955  -0.063 0.949603    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2365585)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>Se interpretan los resultados.</p>
<p>Un modelo estimado con <code>svyglm</code> no genera la R-Cuadrada convencional como si hubiera sido estimado por MCO. La razón principal es que <code>svyglm</code> no estima mediante MCO sino con pseudo-máxima verosimilitud y varianzas robustas que se ajustan considerando el diseño complejo de la encuesta: estratos, unidades primarias de muestreo, pesos de expansión y efectos de conglomeración.</p>
<p>En su lugar, la función indica la estimación de la varianza residual del modelo que permite, entre otros, reflejar cuánta variabilidad queda en la variable objetivo después de considerar las variables explicativas. Asimismo, indica el número de iteraciones necesarias para encontrar la solución al modelo.</p>
<p>Ahora bien, los resultados pueden interpretarse como sigue.</p>
<p>Con respecto a la educación, los resultados muestran una diferencia salarial relativa entre jóvenes egresados (que reportan ingresos) por nivel educativo. Por ejemplo, el ingreso mensual de un jóven egresado de licenciatura es aproximadamente 12.6% mayor a uno egresado de técnico superior, al nivel de confianzan del 90%. Se observa que conforme aumenta el nivel educativo, de tipo terciario, la diferencia salarial relativa es estadísticamente significativa y mayor. Por ejemplo, el jóven egresado de doctorado percibe un 30.9% aproximado de ingreso mensual mayor a uno con estudios de técnico superior.</p>
<p>En cuanto al otro componente de capital humano (experiencia laboral), los resultados muestran que un año adicional en la experiencia laboral se asocia con un incremento de 6.0% en el ingreso mensual del joven egresado. Por otro lado, un incremento del 1% en las horas laborales se asocia con un aumento del 0.11% en el ingreso mensual. [VALIDAR INTERPRETACIÓN]</p>
<p>Con respecto a las características individuales, se observa que existe una diferencia salarial estadísticamente significativa por género y por posición en el hogar. En el primer caso, el salario mensual de una mujer es aproximadamente, en promedio, 10.5% menos comparado con el de un hombre. Por su parte, un joven egresado establecido como jefe de hogar percibe un salario relativamente mayor comparado (12.5% aproximado) con aquellos que no lo son. El caso del estado conyugal, no se observa una diferencia significativa en la población objetivo.</p>
<p>Por su parte, también se observa una diferencia salarial relativa significativa entre las distintas regiones del país. En específico, existe una diferencia relativamente mayor entre la región sur (grupo base) y la región norte debido a los jóvenes egresados ubicados en la región norte perciben, en promedio, 21.5% adicional comparado con los ubicados en la zona sur del país.</p>
<p>En cuanto a las carreras educativas, no se presenta una diferencia salarial significativa en las siguientes carreras, comparado con los jóvenes egresados de las carreras relacionadas a servicios: 2, 5 y 8. En contraparte, los individuos egresados de las carreras vinculadas a 7 perciben, en promedio, un salario mensual 13.7% mayor comparado con los egresados de servicios.</p>
<p>Por el lado de las variables que describen las características de la ocupación, se observa que la mayoría de ellas son estadísticamente significativas. En cuanto a la ocupación como tal, los jóvenes ubicados en la división 9 tienen un ingreso 41.0% mayor con respecto a los que están en la división 1.</p>
<p>Por su parte, aquellos posicionados como empleadores o trabajadores por cuenta propia perciben, en promedio, un salario relativamente mayor con respecto aquellos como trabajadores subordinados y remunerados.</p>
<p>En cuanto al sector económico, no existen diferencias salariales significativas.</p>
<p>Por su parte, el tamaño de la unidad económica explica una diferencia salarial donde, por ejemplo, el salario de los jóvenes egresados ocupados en el gobierno es, en promedio, 36.9% mayor comparado con los ubicados en micronegocios.</p>
<p>También, la condición de informalidad se asocia con una diferencia salarial. Los individuos ocupados bajo la informalidad perciben, en promedio, 30.7% menos salario con respecto a aquellos que no lo están.</p>
<p>De igual modo, la duración de la jornada laboral así como el tipo de unidad económica presentan diferencias salariales significativas.</p>
<p>Con respecto a la variable de interés, los resultados muestran que aquellos jóvenes egresados en situación de sobrecalificación perciben un ingreso mensual relativamente menor comparado con aquellos que no lo están. En específico, el salario de un joven sobrecalificado es aproximadamente, en promedio, 19.2% menor siendo significativo al nivel de confianza del 99.9%. Por su parte, no se observa una diferencia entre los jóvenes subcalificados y sin desajuste.</p>
<p>Estos resultados muestran que la sobrecalificación se asocia con una pérdida salarial relativa. En específico, los jóvenes egresados (que reportan ingreso) ubicados en ocupaciones que requieren una educación menor a la que poseen es 19.2% comparado con aquellos que no presentan desajuste educativo.</p>
<p>Ahora, se analizará si la pérdida salarial de la sobrecalificación es heterogénea por nivel educativo, género y región.</p>
<p>POR NIVEL EDUCATIVO</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_edu <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    over_obj <span class="sc">*</span> educacion <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> mujer <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> regiones <span class="sc">+</span> campo_amplio <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> informal <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_edu)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ over_obj * educacion + 
    under_obj + exper + I(exper^2) + log(horas_lab) + mujer + 
    casada + jefe_hogar + regiones + campo_amplio + division + 
    pos_ocu + sector_eco + tamanio + informal + jornada + unidad_eco, 
    design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          8.2544938  0.2116787  38.995  &lt; 2e-16 ***
over_obj            -0.0962429  0.1218814  -0.790 0.429771    
educacion7           0.1901889  0.0925479   2.055 0.039924 *  
educacion8           0.3658284  0.1107943   3.302 0.000967 ***
educacion9           0.3593716  0.1339912   2.682 0.007340 ** 
under_obj            0.1543341  0.1247428   1.237 0.216061    
exper                0.0596011  0.0158798   3.753 0.000176 ***
I(exper^2)          -0.0033810  0.0010864  -3.112 0.001867 ** 
log(horas_lab)       0.1118495  0.0630955   1.773 0.076335 .  
mujer               -0.1054096  0.0214489  -4.914 9.17e-07 ***
casada               0.0375652  0.0235892   1.592 0.111338    
jefe_hogar           0.1251523  0.0219960   5.690 1.34e-08 ***
regiones2            0.1205108  0.0308946   3.901 9.71e-05 ***
regiones3            0.0514422  0.0289538   1.777 0.075675 .  
regiones4            0.2152916  0.0256883   8.381  &lt; 2e-16 ***
regiones5            0.0769853  0.0272803   2.822 0.004790 ** 
campo_amplio02       0.0642511  0.0511023   1.257 0.208699    
campo_amplio03       0.0662992  0.0362852   1.827 0.067731 .  
campo_amplio04       0.1188648  0.0339346   3.503 0.000464 ***
campo_amplio05       0.0335810  0.0794972   0.422 0.672738    
campo_amplio06       0.1170548  0.0547953   2.136 0.032707 *  
campo_amplio07       0.1378934  0.0367931   3.748 0.000180 ***
campo_amplio08       0.0834594  0.1038570   0.804 0.421665    
campo_amplio09       0.0935111  0.0379517   2.464 0.013773 *  
campo_amplio10       0.0795418  0.0456789   1.741 0.081684 .  
campo_amplio99       0.2276000  0.1007566   2.259 0.023929 *  
division2           -0.0867072  0.0436083  -1.988 0.046828 *  
division3           -0.1996211  0.0520719  -3.834 0.000128 ***
division4           -0.2874266  0.0543094  -5.292 1.26e-07 ***
division5           -0.1882892  0.0578232  -3.256 0.001136 ** 
division6           -0.3657464  0.1559643  -2.345 0.019060 *  
division7           -0.1677629  0.0776013  -2.162 0.030674 *  
division8           -0.3314533  0.0605057  -5.478 4.50e-08 ***
division9           -0.4097823  0.0716026  -5.723 1.10e-08 ***
pos_ocu2             0.4362338  0.0609588   7.156 9.42e-13 ***
pos_ocu3             0.0856756  0.0488267   1.755 0.079371 .  
sector_eco2         -0.0916389  0.0732650  -1.251 0.211067    
sector_eco3         -0.0320515  0.0709250  -0.452 0.651354    
sector_eco4         -0.1407818  0.1854683  -0.759 0.447849    
tamanio4             0.0945327  0.0345991   2.732 0.006312 ** 
tamanio5             0.1469079  0.0396505   3.705 0.000213 ***
tamanio6             0.2804298  0.0460132   6.095 1.17e-09 ***
tamanio7             0.3706986  0.0545112   6.800 1.16e-11 ***
tamanio8             0.0002003  0.0423297   0.005 0.996225    
informal1           -0.3079144  0.0259403 -11.870  &lt; 2e-16 ***
jornada3             0.4741966  0.0985941   4.810 1.55e-06 ***
jornada4             0.5030826  0.1228990   4.093 4.31e-05 ***
jornada5             0.4937874  0.1395606   3.538 0.000406 ***
unidad_eco2         -0.1850624  0.0343900  -5.381 7.71e-08 ***
unidad_eco3         -0.1195743  0.0455828  -2.623 0.008735 ** 
unidad_eco4         -0.0094629  0.1342733  -0.070 0.943818    
over_obj:educacion7 -0.0931413  0.1227920  -0.759 0.448168    
over_obj:educacion8 -0.1696015  0.1463106  -1.159 0.246432    
over_obj:educacion9 -0.0414276  0.3597692  -0.115 0.908330    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2364611)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>Se realiza contraste de wald [PENDIENTE DE INVESTIGAR]</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regTermTest</span>(model_jov_svy_edu, <span class="sc">~</span> over_obj<span class="sc">:</span>educacion)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test for over_obj:educacion
 in svyglm(formula = log(ingreso_mensual) ~ over_obj * educacion + 
    under_obj + exper + I(exper^2) + log(horas_lab) + mujer + 
    casada + jefe_hogar + regiones + campo_amplio + division + 
    pos_ocu + sector_eco + tamanio + informal + jornada + unidad_eco, 
    design = jovenes_svy_reg)
F =  0.485252  on  3  and  5325  df: p= 0.69253 </code></pre>
</div>
</div>
<p>Recordemos que <span class="math inline">\(H0\)</span>: no existe efecto heterogéneo</p>
<p>Los resultados muestran que no existe un efecto heterogéneo de la sobrecalificación por nivel educativo</p>
<p>POR GÉNERO</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_muj <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    educacion <span class="sc">+</span> over_obj <span class="sc">*</span> mujer <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> regiones <span class="sc">+</span> campo_amplio <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> informal <span class="sc">+</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_muj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    mujer + under_obj + exper + I(exper^2) + log(horas_lab) + 
    casada + jefe_hogar + regiones + campo_amplio + division + 
    pos_ocu + sector_eco + tamanio + informal + jornada + unidad_eco, 
    design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     8.3019937  0.2041653  40.663  &lt; 2e-16 ***
educacion7      0.1248433  0.0662633   1.884 0.059613 .  
educacion8      0.2784710  0.0821368   3.390 0.000703 ***
educacion9      0.3086935  0.1334255   2.314 0.020727 *  
over_obj       -0.1674775  0.0371791  -4.505 6.79e-06 ***
mujer          -0.0786726  0.0323074  -2.435 0.014919 *  
under_obj       0.0903399  0.1044668   0.865 0.387204    
exper           0.0601948  0.0158278   3.803 0.000144 ***
I(exper^2)     -0.0034198  0.0010844  -3.154 0.001622 ** 
log(horas_lab)  0.1121519  0.0627649   1.787 0.074018 .  
casada          0.0364446  0.0236769   1.539 0.123803    
jefe_hogar      0.1256659  0.0220721   5.693 1.31e-08 ***
regiones2       0.1215111  0.0308639   3.937 8.36e-05 ***
regiones3       0.0526835  0.0289340   1.821 0.068691 .  
regiones4       0.2153648  0.0256769   8.388  &lt; 2e-16 ***
regiones5       0.0779888  0.0272272   2.864 0.004195 ** 
campo_amplio02  0.0647878  0.0511060   1.268 0.204956    
campo_amplio03  0.0700146  0.0359849   1.946 0.051748 .  
campo_amplio04  0.1216638  0.0343555   3.541 0.000402 ***
campo_amplio05  0.0378963  0.0783033   0.484 0.628428    
campo_amplio06  0.1203964  0.0548696   2.194 0.028262 *  
campo_amplio07  0.1397465  0.0369205   3.785 0.000155 ***
campo_amplio08  0.0811521  0.1032302   0.786 0.431828    
campo_amplio09  0.0942201  0.0383091   2.459 0.013946 *  
campo_amplio10  0.0809723  0.0456393   1.774 0.076091 .  
campo_amplio99  0.2261236  0.1016739   2.224 0.026190 *  
division2      -0.0882141  0.0439455  -2.007 0.044763 *  
division3      -0.1959302  0.0521969  -3.754 0.000176 ***
division4      -0.2865855  0.0543794  -5.270 1.42e-07 ***
division5      -0.1889215  0.0581116  -3.251 0.001157 ** 
division6      -0.3712765  0.1565154  -2.372 0.017721 *  
division7      -0.1717389  0.0779631  -2.203 0.027650 *  
division8      -0.3381021  0.0606882  -5.571 2.66e-08 ***
division9      -0.4103625  0.0713717  -5.750 9.44e-09 ***
pos_ocu2        0.4408114  0.0612274   7.200 6.88e-13 ***
pos_ocu3        0.0875094  0.0490366   1.785 0.074387 .  
sector_eco2    -0.0892203  0.0734410  -1.215 0.224474    
sector_eco3    -0.0302239  0.0708221  -0.427 0.669573    
sector_eco4    -0.1325790  0.1844737  -0.719 0.472365    
tamanio4        0.0940612  0.0346200   2.717 0.006610 ** 
tamanio5        0.1486733  0.0394306   3.771 0.000165 ***
tamanio6        0.2827442  0.0458603   6.165 7.55e-10 ***
tamanio7        0.3728765  0.0543771   6.857 7.82e-12 ***
tamanio8        0.0007564  0.0422315   0.018 0.985712    
informal1      -0.3069807  0.0260059 -11.804  &lt; 2e-16 ***
jornada3        0.4735890  0.0982495   4.820 1.47e-06 ***
jornada4        0.5008496  0.1224300   4.091 4.36e-05 ***
jornada5        0.4902010  0.1389854   3.527 0.000424 ***
unidad_eco2    -0.1882119  0.0343568  -5.478 4.50e-08 ***
unidad_eco3    -0.1197544  0.0454995  -2.632 0.008513 ** 
unidad_eco4    -0.0188802  0.1342833  -0.141 0.888191    
over_obj:mujer -0.0488483  0.0402205  -1.215 0.224606    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2364233)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regTermTest</span>(model_jov_svy_muj, <span class="sc">~</span> over_obj<span class="sc">:</span>mujer)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test for over_obj:mujer
 in svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    mujer + under_obj + exper + I(exper^2) + log(horas_lab) + 
    casada + jefe_hogar + regiones + campo_amplio + division + 
    pos_ocu + sector_eco + tamanio + informal + jornada + unidad_eco, 
    design = jovenes_svy_reg)
F =  1.475039  on  1  and  5327  df: p= 0.22461 </code></pre>
</div>
</div>
<p>Tampoco existe un efecto heterogéneo por género</p>
<p>POR CARRERAS</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_car <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    educacion <span class="sc">+</span> over_obj <span class="sc">*</span> campo_amplio <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> mujer <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> regiones <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> informal <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    campo_amplio + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + regiones + division + pos_ocu + 
    sector_eco + tamanio + informal + jornada + unidad_eco, design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              8.363250   0.204620  40.872  &lt; 2e-16 ***
educacion7               0.118971   0.066100   1.800 0.071938 .  
educacion8               0.277771   0.080934   3.432 0.000604 ***
educacion9               0.315325   0.136691   2.307 0.021101 *  
over_obj                -0.267880   0.059122  -4.531 6.00e-06 ***
campo_amplio02           0.048233   0.065264   0.739 0.459911    
campo_amplio03           0.009319   0.050255   0.185 0.852891    
campo_amplio04           0.085704   0.050670   1.691 0.090817 .  
campo_amplio05          -0.072570   0.131617  -0.551 0.581404    
campo_amplio06           0.170588   0.083797   2.036 0.041827 *  
campo_amplio07           0.061750   0.051891   1.190 0.234103    
campo_amplio08           0.042716   0.125799   0.340 0.734200    
campo_amplio09           0.068172   0.048943   1.393 0.163712    
campo_amplio10          -0.015226   0.058630  -0.260 0.795107    
campo_amplio99          -0.123314   0.088043  -1.401 0.161385    
under_obj                0.056320   0.106403   0.529 0.596612    
exper                    0.059913   0.015725   3.810 0.000141 ***
I(exper^2)              -0.003417   0.001079  -3.168 0.001546 ** 
log(horas_lab)           0.110213   0.062921   1.752 0.079900 .  
mujer                   -0.108062   0.021208  -5.095 3.60e-07 ***
casada                   0.036931   0.023577   1.566 0.117315    
jefe_hogar               0.124283   0.021972   5.657 1.63e-08 ***
regiones2                0.119881   0.030647   3.912 9.28e-05 ***
regiones3                0.053485   0.028617   1.869 0.061682 .  
regiones4                0.215137   0.025767   8.349  &lt; 2e-16 ***
regiones5                0.078628   0.027632   2.846 0.004450 ** 
division2               -0.094484   0.045300  -2.086 0.037050 *  
division3               -0.199560   0.052633  -3.792 0.000151 ***
division4               -0.286752   0.054832  -5.230 1.76e-07 ***
division5               -0.191965   0.058353  -3.290 0.001009 ** 
division6               -0.377079   0.155279  -2.428 0.015199 *  
division7               -0.180201   0.078516  -2.295 0.021768 *  
division8               -0.342293   0.061560  -5.560 2.82e-08 ***
division9               -0.412087   0.072554  -5.680 1.42e-08 ***
pos_ocu2                 0.440030   0.061105   7.201 6.80e-13 ***
pos_ocu3                 0.092570   0.048935   1.892 0.058586 .  
sector_eco2             -0.083320   0.073374  -1.136 0.256192    
sector_eco3             -0.030531   0.070900  -0.431 0.666765    
sector_eco4             -0.170347   0.197732  -0.862 0.388998    
tamanio4                 0.092995   0.034890   2.665 0.007714 ** 
tamanio5                 0.147943   0.039477   3.748 0.000180 ***
tamanio6                 0.280971   0.045903   6.121 9.96e-10 ***
tamanio7                 0.378759   0.055336   6.845 8.53e-12 ***
tamanio8                 0.006382   0.041796   0.153 0.878641    
informal1               -0.303922   0.026154 -11.621  &lt; 2e-16 ***
jornada3                 0.476145   0.098103   4.853 1.25e-06 ***
jornada4                 0.513112   0.122106   4.202 2.69e-05 ***
jornada5                 0.500317   0.138586   3.610 0.000309 ***
unidad_eco2             -0.189408   0.034254  -5.529 3.37e-08 ***
unidad_eco3             -0.121257   0.045650  -2.656 0.007926 ** 
unidad_eco4              0.030748   0.134349   0.229 0.818981    
over_obj:campo_amplio02  0.030776   0.100738   0.306 0.759991    
over_obj:campo_amplio03  0.111155   0.075531   1.472 0.141173    
over_obj:campo_amplio04  0.070268   0.066657   1.054 0.291853    
over_obj:campo_amplio05  0.223441   0.146190   1.528 0.126466    
over_obj:campo_amplio06 -0.113321   0.101738  -1.114 0.265397    
over_obj:campo_amplio07  0.136455   0.070296   1.941 0.052293 .  
over_obj:campo_amplio08  0.075655   0.177601   0.426 0.670136    
over_obj:campo_amplio09  0.047261   0.074604   0.633 0.526436    
over_obj:campo_amplio10  0.142887   0.081376   1.756 0.079166 .  
over_obj:campo_amplio99  0.475213   0.131917   3.602 0.000318 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2354344)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regTermTest</span>(model_jov_svy_car, <span class="sc">~</span> over_obj<span class="sc">:</span>campo_amplio)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test for over_obj:campo_amplio
 in svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    campo_amplio + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + regiones + division + pos_ocu + 
    sector_eco + tamanio + informal + jornada + unidad_eco, design = jovenes_svy_reg)
F =  2.458944  on  10  and  5318  df: p= 0.0062643 </code></pre>
</div>
</div>
<p>Se rechaza HO. Es decir, existe un efecto heterogéneo por carrera educativa. Sin embargo, solamente en dos carreras esta diferencia es significativa. En específico, la pérdida salarial de la sobrecalificación de los jóvenes egresados de la carrera 7 (ingeniería, manufactura y construcción) es 13.6% menor comparado con aquellos egresados de la carrera de educación, es decir, la pérdida salarial de los jóvenes egresados de la carrera 7 sobrecalificados es, en promedio, 8.9%</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.267880</span>) <span class="sc">-</span> <span class="dv">1</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2350004</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.136455</span>) <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1462033</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">0.2350004</span> <span class="sc">+</span> <span class="fl">0.1462033</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0887971</code></pre>
</div>
</div>
<p>Asimismo, también existe una pérdida salarial significativamente distinta en jóvenes egresados de la carrera 10 (servicios).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.142887</span>) <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1535994</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">0.2350004</span> <span class="sc">+</span> <span class="fl">0.1535994</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.081401</code></pre>
</div>
</div>
<p>Ambos son significativos al nivel de confianza del 90%</p>
<p>POR REGIONES</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_reg <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    educacion <span class="sc">+</span> over_obj <span class="sc">*</span> regiones <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> mujer <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> campo_amplio <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> informal <span class="sc">+</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_reg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    regiones + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + campo_amplio + division + pos_ocu + 
    sector_eco + tamanio + informal + jornada + unidad_eco, design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         8.324e+00  2.037e-01  40.862  &lt; 2e-16 ***
educacion7          1.220e-01  6.666e-02   1.831 0.067215 .  
educacion8          2.733e-01  8.233e-02   3.319 0.000910 ***
educacion9          3.065e-01  1.349e-01   2.272 0.023127 *  
over_obj           -1.873e-01  4.204e-02  -4.455 8.55e-06 ***
regiones2           1.428e-01  4.638e-02   3.078 0.002093 ** 
regiones3           4.624e-02  4.155e-02   1.113 0.265809    
regiones4           2.004e-01  3.547e-02   5.649 1.69e-08 ***
regiones5           7.728e-02  4.316e-02   1.790 0.073448 .  
under_obj           7.907e-02  1.096e-01   0.721 0.470750    
exper               6.042e-02  1.578e-02   3.830 0.000130 ***
I(exper^2)         -3.427e-03  1.081e-03  -3.171 0.001530 ** 
log(horas_lab)      1.117e-01  6.322e-02   1.768 0.077201 .  
mujer              -1.055e-01  2.143e-02  -4.924 8.73e-07 ***
casada              3.664e-02  2.354e-02   1.556 0.119660    
jefe_hogar          1.237e-01  2.230e-02   5.548 3.02e-08 ***
campo_amplio02      6.223e-02  5.080e-02   1.225 0.220642    
campo_amplio03      6.381e-02  3.622e-02   1.761 0.078211 .  
campo_amplio04      1.157e-01  3.392e-02   3.411 0.000652 ***
campo_amplio05      2.791e-02  7.880e-02   0.354 0.723176    
campo_amplio06      1.107e-01  5.340e-02   2.072 0.038276 *  
campo_amplio07      1.346e-01  3.673e-02   3.666 0.000249 ***
campo_amplio08      7.680e-02  1.033e-01   0.744 0.457140    
campo_amplio09      8.788e-02  3.767e-02   2.333 0.019709 *  
campo_amplio10      7.814e-02  4.558e-02   1.715 0.086485 .  
campo_amplio99      2.251e-01  1.043e-01   2.158 0.030975 *  
division2          -8.610e-02  4.353e-02  -1.978 0.047979 *  
division3          -2.004e-01  5.185e-02  -3.865 0.000112 ***
division4          -2.858e-01  5.412e-02  -5.281 1.33e-07 ***
division5          -1.878e-01  5.809e-02  -3.234 0.001230 ** 
division6          -3.653e-01  1.538e-01  -2.375 0.017568 *  
division7          -1.678e-01  7.729e-02  -2.171 0.030011 *  
division8          -3.347e-01  6.004e-02  -5.574 2.61e-08 ***
division9          -4.069e-01  7.080e-02  -5.747 9.57e-09 ***
pos_ocu2            4.353e-01  6.124e-02   7.108 1.34e-12 ***
pos_ocu3            8.200e-02  4.875e-02   1.682 0.092614 .  
sector_eco2        -9.141e-02  7.238e-02  -1.263 0.206691    
sector_eco3        -3.269e-02  6.998e-02  -0.467 0.640438    
sector_eco4        -1.407e-01  1.822e-01  -0.773 0.439745    
tamanio4            9.373e-02  3.468e-02   2.703 0.006897 ** 
tamanio5            1.447e-01  3.969e-02   3.645 0.000270 ***
tamanio6            2.794e-01  4.606e-02   6.066 1.40e-09 ***
tamanio7            3.697e-01  5.492e-02   6.731 1.86e-11 ***
tamanio8            3.517e-05  4.225e-02   0.001 0.999336    
informal1          -3.076e-01  2.597e-02 -11.843  &lt; 2e-16 ***
jornada3            4.733e-01  9.877e-02   4.792 1.70e-06 ***
jornada4            5.025e-01  1.231e-01   4.083 4.50e-05 ***
jornada5            4.935e-01  1.396e-01   3.536 0.000410 ***
unidad_eco2        -1.850e-01  3.443e-02  -5.371 8.15e-08 ***
unidad_eco3        -1.170e-01  4.563e-02  -2.564 0.010364 *  
unidad_eco4        -1.567e-02  1.331e-01  -0.118 0.906244    
over_obj:regiones2 -4.196e-02  6.142e-02  -0.683 0.494535    
over_obj:regiones3  1.005e-02  5.391e-02   0.186 0.852104    
over_obj:regiones4  2.953e-02  4.662e-02   0.634 0.526415    
over_obj:regiones5  8.520e-04  5.356e-02   0.016 0.987309    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2363815)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regTermTest</span>(model_jov_svy_reg, <span class="sc">~</span> over_obj<span class="sc">:</span>regiones)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test for over_obj:regiones
 in svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    regiones + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + campo_amplio + division + pos_ocu + 
    sector_eco + tamanio + informal + jornada + unidad_eco, design = jovenes_svy_reg)
F =  0.3936023  on  4  and  5324  df: p= 0.81337 </code></pre>
</div>
</div>
<p>Por regiones no existe un efecto significativo</p>
<p>Por último, por condición de informalidad</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model_jov_svy_informal <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(ingreso_mensual) <span class="sc">~</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    educacion <span class="sc">+</span> over_obj <span class="sc">*</span> informal <span class="sc">+</span> under_obj <span class="sc">+</span> exper <span class="sc">+</span> <span class="fu">I</span>(exper<span class="sc">**</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(horas_lab) <span class="sc">+</span> mujer <span class="sc">+</span> casada <span class="sc">+</span> jefe_hogar <span class="sc">+</span> campo_amplio <span class="sc">+</span> regiones <span class="sc">+</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    division <span class="sc">+</span> pos_ocu <span class="sc">+</span> sector_eco <span class="sc">+</span> tamanio <span class="sc">+</span> </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    jornada <span class="sc">+</span> unidad_eco, </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> jovenes_svy_reg</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_jov_svy_informal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    informal + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + campo_amplio + regiones + division + 
    pos_ocu + sector_eco + tamanio + jornada + unidad_eco, design = jovenes_svy_reg)

Survey design:
Called via srvyr

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         8.319359   0.204440  40.693  &lt; 2e-16 ***
educacion7          0.125402   0.066310   1.891 0.058658 .  
educacion8          0.279444   0.082587   3.384 0.000721 ***
educacion9          0.307593   0.133342   2.307 0.021105 *  
over_obj           -0.194808   0.033972  -5.734 1.03e-08 ***
informal1          -0.314480   0.039261  -8.010 1.40e-15 ***
under_obj           0.089285   0.107058   0.834 0.404325    
exper               0.060432   0.015831   3.817 0.000136 ***
I(exper^2)         -0.003437   0.001084  -3.170 0.001532 ** 
log(horas_lab)      0.112913   0.063020   1.792 0.073238 .  
mujer              -0.105508   0.021478  -4.912 9.27e-07 ***
casada              0.036253   0.023645   1.533 0.125279    
jefe_hogar          0.124653   0.022071   5.648 1.71e-08 ***
campo_amplio02      0.064428   0.051073   1.261 0.207188    
campo_amplio03      0.066503   0.036411   1.826 0.067841 .  
campo_amplio04      0.119292   0.034023   3.506 0.000458 ***
campo_amplio05      0.034646   0.078543   0.441 0.659147    
campo_amplio06      0.116192   0.054626   2.127 0.033462 *  
campo_amplio07      0.137611   0.036861   3.733 0.000191 ***
campo_amplio08      0.080286   0.103345   0.777 0.437271    
campo_amplio09      0.093104   0.038134   2.442 0.014659 *  
campo_amplio10      0.080952   0.045900   1.764 0.077845 .  
campo_amplio99      0.224734   0.103082   2.180 0.029289 *  
regiones2           0.120917   0.030911   3.912 9.28e-05 ***
regiones3           0.051255   0.028990   1.768 0.077114 .  
regiones4           0.215030   0.025698   8.368  &lt; 2e-16 ***
regiones5           0.077231   0.027273   2.832 0.004646 ** 
division2          -0.087547   0.044390  -1.972 0.048635 *  
division3          -0.199892   0.052735  -3.790 0.000152 ***
division4          -0.289002   0.054440  -5.309 1.15e-07 ***
division5          -0.190747   0.058207  -3.277 0.001056 ** 
division6          -0.366062   0.156102  -2.345 0.019063 *  
division7          -0.167346   0.077586  -2.157 0.031058 *  
division8          -0.330585   0.060822  -5.435 5.71e-08 ***
division9          -0.409849   0.071690  -5.717 1.14e-08 ***
pos_ocu2            0.438300   0.061015   7.183 7.73e-13 ***
pos_ocu3            0.086715   0.048845   1.775 0.075906 .  
sector_eco2        -0.090706   0.073313  -1.237 0.216051    
sector_eco3        -0.031438   0.071076  -0.442 0.658283    
sector_eco4        -0.142328   0.186498  -0.763 0.445400    
tamanio4            0.095078   0.034964   2.719 0.006563 ** 
tamanio5            0.147611   0.039929   3.697 0.000220 ***
tamanio6            0.281223   0.046202   6.087 1.23e-09 ***
tamanio7            0.370572   0.054608   6.786 1.28e-11 ***
tamanio8            0.001076   0.042227   0.025 0.979680    
jornada3            0.471486   0.098978   4.764 1.95e-06 ***
jornada4            0.499335   0.123197   4.053 5.13e-05 ***
jornada5            0.488438   0.139820   3.493 0.000481 ***
unidad_eco2        -0.185791   0.034457  -5.392 7.27e-08 ***
unidad_eco3        -0.121724   0.045780  -2.659 0.007864 ** 
unidad_eco4        -0.010252   0.135292  -0.076 0.939602    
over_obj:informal1  0.012348   0.047979   0.257 0.796915    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2365522)

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regTermTest</span>(model_jov_svy_informal, <span class="sc">~</span> over_obj<span class="sc">:</span>informal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wald test for over_obj:informal
 in svyglm(formula = log(ingreso_mensual) ~ educacion + over_obj * 
    informal + under_obj + exper + I(exper^2) + log(horas_lab) + 
    mujer + casada + jefe_hogar + campo_amplio + regiones + division + 
    pos_ocu + sector_eco + tamanio + jornada + unidad_eco, design = jovenes_svy_reg)
F =  0.06623168  on  1  and  5327  df: p= 0.79691 </code></pre>
</div>
</div>
<p>Tampoco lo es</p>
<p>En resumen, los resultados muestran la existencia de una pérdida salarial de la sobrecalificación en jóvenes egresados de educación superior. En promedio, los jóvenes asignados en ocupaciones que requieren una educación menor perciben un salario mensual 17.5% menos comparado con aquellos que no presentan desajuste entre la educación individual y la requerida. Asimismo, se observa un efecto heterogéneo por carreras educativas donde la pérdida salarial de la sobrecalificación de jóvenes egresados de las carreras 7 y 10 es relativamente menor comparado con los individuos egresados de la carrera de educación. No obstante, no se observa un efecto salarial heterogéneo por nivel educativo, género, por regiones, ni por condición de informalidad.</p>
<p>Por tanto, no se rechaza la hipótesis central de la presente investigación, es decir, en jóvenes egresados de educación superior también existe una pérdida salarial relacionada a la sobrecalificación donde el salario (mensual) de los jóvenes sobrecalificados es, en promedio, 17.5% menor con respecto al salario de los jóvenes sin desajuste educativo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.1920406</span>) <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1747266</code></pre>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>