---
date: today
format: html
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(writexl)
library(readxl)
# trabajar encuesta compleja dentro de tidyverse 
library(srvyr)
# regresión a encuesta compleja
library(survey)

source("C:/Prog/tesis/scripts/0_funciones_v9.R")

# tabla sociodemográfica
sdem <- read_csv(
  "datos/ENOE_SDEMT225.csv",
  col_types = cols(.default = col_character())
)

# tabla de ocupación y empleo I
coe1 <- read_csv(
  "datos/ENOE_COE1T225.csv",
  col_types = cols(.default = col_character())
)

# tabla de ocupación y empleo II
coe2 <- read_csv(
  "datos/ENOE_COE2T225.csv",
  col_types = cols(.default = col_character())
)


sinco11_ciuo08 <- read_csv(
  "C:/Prog/tesis/datos/sinco11_a_ciuo08.csv",
  col_types = cols(.default = col_character())
)

sinco19_11 <- read_csv(
  "C:/Prog/tesis/datos/sinco19_a_sinco11.csv",
  col_types = cols(.default = col_character())
)

# ciuo08 <- read_xlsx(
#   "C:/Prog/tesis/datos/ISCO.xlsx",
#   sheet = 2,
#   col_types = "text"
# )

# población de 12 y más para unir sdem y coe INEGI(2023:9)
pob_12ymas <- sdem |> 
  mutate(edad = as.integer(eda)) |> 
  filter(
    r_def == "0",
    c_res != "2",
    between(edad, 12, 98)
  )

# unión de sdem y coe INEGI(2023:9)
completo <- pob_12ymas |>
  full_join(coe1, by = c("tipo", "mes_cal", "cd_a", "ent", "con", "v_sel", "n_hog", "h_mud", "n_ren")) |>
  full_join(coe2, by = c("tipo", "mes_cal", "cd_a", "ent", "con", "v_sel", "n_hog", "h_mud", "n_ren"))

# población de 15 años y más INEGI(2023:21)
# para seleccionar población ocupada INEGI(2023:21)
pob_15ymas <- completo |> 
  filter(
    r_def.x == "0",
    c_res != "2",
    between(edad, 15, 98)
  )

# población ocupada INEGI(2023: 21)
ocupada <- pob_15ymas |> 
  filter(clase2 == 1)

## Enfoque normativo de OIT en la población ocupada
ocupada_normativo <- construir_variables_ind(ocupada)
ocupada_normativo <- construir_variables_ocu(ocupada_normativo)
ocupada_normativo <- construir_educacion_cine11(ocupada_normativo)
jovenes <- seleccionar_jov(ocupada_normativo)
```

SINCO-11

```{r}
sinco11 <- sinco11_ciuo08 |> 
  filter(str_length(sinco11) == 4) |>
  mutate(
    c08_major = str_sub(ciuo08, 1, 1),
    c08_submajor = str_sub(ciuo08, 1, 2),
    skill_level = case_when(
        # skill level 4
        c08_submajor == "11" | c08_submajor == "12" |
          c08_submajor == "13" | c08_major == "2" |
          c08_submajor == "01" ~ "4",
        # skill level 3
        c08_submajor == "14" | c08_major == "3" ~ "3",
        # skill level 2
        c08_major == "4" | c08_major == "5" |
          c08_major == "6" | c08_major == "7" |
          c08_major == "8" | c08_submajor == "02" ~ "2",
        # skill level 1
        c08_major == "9" | c08_submajor == "03" ~ "1",
        TRUE ~ NA
      ) 
  ) |>  
  group_by(sinco11) |> 
  mutate(id = row_number()) |> 
  ungroup() |> 
  pivot_wider(
    id_cols = sinco11,
    names_from = id,
    names_prefix = "skill_",
    values_from = skill_level,
    values_fill = ""
  )
```

SINCO-19

```{r}
sinco19 <- sinco19_11 |> 
  left_join(sinco11, by = c("sinco_11" = "sinco11")) |> 
  filter(str_length(sinco_19) == 4) |> 
  group_by(sinco_19) |> 
  mutate(id = row_number()) |> 
  ungroup() |> 
  pivot_wider(
    id_cols = sinco_19,
    names_from = id,
    values_from = skill_1:skill_7,
    values_fill = ""
  ) |> 
  # concatena distintas columnas
  unite("skill_level", skill_1_1:skill_7_2, sep = "") |> 
  mutate(
    # extrae el primer caracter
    skill_min = str_sub(skill_level, 1, 1),
    # extrae el último caracter
    skill_max = str_sub(skill_level, str_length(skill_level)), 
    edu_req_min = case_when(
      # licenciatura
      skill_min == "4" ~ "7",
      # técnico superior
      skill_min == "3" ~ "6",
      # secundaria
      skill_min == "2" ~ "3",
      # preescolar 
      skill_min == "1" ~ "1",
      TRUE ~ NA
    ),
    edu_req_max = case_when(
      # doctorado
      skill_max == "4" ~ "9",
      # técnico superior
      skill_max == "3" ~ "6",
      # secundaria
      skill_max == "2" ~ "4",
      # preescolar 
      skill_max == "1" ~ "2",
      TRUE ~ NA
    )
  ) |> 
  # añadir descripción
  left_join(sinco19_11, by = "sinco_19", multiple = "any") |>
  mutate(
    descripcion_sinco19 = str_remove(descripcion_sinco19, "- ")
  ) |>
  select(contains("19"), contains("edu"))
```

Unión

```{r}
jovenes <- jovenes |> 
  left_join(sinco19, by = c("p3" = "sinco_19")) |> 
  mutate(
      educacion = as.integer(educacion),
      objetivo_min2 = as.integer(edu_req_min),
      objetivo_max2 = as.integer(edu_req_max),
      edu_mismatch_obj2 = case_when(
        # required
        between(educacion, objetivo_min2, objetivo_max2) ~ 0,
        # over
        educacion > objetivo_max2 ~ 1,
        # under
        educacion < objetivo_min2 ~ 2,
        TRUE ~ NA
      ),
      # variables binarias
      over_obj = if_else(educacion > objetivo_max2, 1, 0),
      required_obj = if_else(between(educacion, objetivo_min2, objetivo_max2), 1, 0),
      under_obj = if_else(educacion < objetivo_min2, 1, 0)
      # variables de años de sobre o infra
      # objetivo: no se puede obtener ya que la educación requerida está en intervalos
  )
```

Incidencia

```{r}
jovenes_svy <- definir_encuesta(jovenes)

calcular_prop(jovenes_svy, edu_mismatch_obj2)
```

Obtengo un resultado diferente ¿por qué?

